### ISSUE TITLE
Slabs and bricks uncraftable and dupe with Hardened Stone (using Chisel)

### ISSUE THREAD

**Issue by Hjaldar** [ValkyrieofNight/EnvironmentalTech#1]
It seems that recently basalt, alabaster and hardened stone have becomes ore-dictionaried with stone.

This means that basalt, alabaster and hardened stone slabs and bricks can no longer be crafted, instead those recipes result in stone slabs and stone bricks.

Also stone can be converted to hardened stone with a chisel from the Chisel mod and then 8 hardened stone converted to 32 stone. Repeat for infinite stone (at the cost of some chisels).

**Comment by ValkyrieofNight** [comment]
Thanks. Have fixed and released a new build.
