### ISSUE TITLE
[Suggest] Rethink power requirements for Void Miners

### ISSUE THREAD

**Issue by xenoflot** [ValkyrieofNight/EnvironmentalTech#10]
Hi,

A player mentioned to me tonight that he felt the Void Miners were drawing a surprisingly low amount of power. We ran the numbers in comparison to the MFR Laser Drill. Assuming I didn't screw up my maths, the Laser Drill produces 1 ore every 15 secs if delivered 20K RF/t. By comparison, a Tier 3 Void Miner produces 1 ore every 15 secs if delivered just 106 RF/t. Even after adding 8 upgrades and boosting the output to about 2 ore per second, it was still only drawing ~5K RF/t.

Everyone has their own idea of balance and I know that we can adjust the configs for our server, but I'd like to suggest you rework the default numbers to be closer to the Laser Drill. Having a constant, passive, effortless source of materials for the cost of keeping a couple of coal generators topped up, seems excessively cheap. 

Also, having built a Tier 4 solar, I've been at a loss for something to do with ~82K RF/t :-)

Cheers and thanks for your hard work and generosity in making this mod!

**Comment by ValkyrieofNight** [comment]
Yeah I do agree with you. I've been working on balancing the numbers for the next update. This has been in the works for a few days. Solars defaults have been nerfed a bit. Void ore miners defaults have been increased. There will be more multiblocks in the future that will help you use all that energy you are genning lol.
