### ISSUE TITLE
[1.12.2] Using Creative to build Solars T2+ uses incorrect solar panels

### ISSUE THREAD

**Issue by Morpheus1101** [ValkyrieofNight/EnvironmentalTech#100]
When i was going through writing out a list of what blocks are needed for what tier, i noticed that T2+ always used the Litherite Solar Panels instead of the next tier Solar Panels

**Comment by mctom987** [comment]
This is probably working as intended. Solar panels work on any tier controller. Thus, you can use Aethium panels in a Tier 1 controller, and Litherite panels in a tier 6 controller.

I believe if you have a panel in your inventory, it will use the highest panel, and will use Litherite if you have none.

**Comment by ValkyrieofNight** [comment]
This is working as intended. The higher tier solar cells just increase the power output of the solar arrays.
