### ISSUE TITLE
question

### ISSUE THREAD

**Issue by CharCharthemonkey** [ValkyrieofNight/EnvironmentalTech#101]
was wondering if the void miners in 1.12.2 are supposed to get ores that were previously turned off in configs but completely ignore their variant ores that are turned on via configs? i ask cause trying to make a modpack where forestry ores are off completely and ud get thermals ores instead but the void ore miner doesnt have thermal ores listed but does do forestry ores

**Comment by ValkyrieofNight** [comment]
The default ores are based on ore dictionary names so when it picks the ore it uses the first available in the ore dictionary for that ore name. If you want you can specify the exact ore you want from the mod that you want in the loot tables found in the configs folder.

**Comment by PG-Fuury** [comment]
CharChar, it sounds like you took a blacklist and thought it was a whitelist
