### ISSUE TITLE
Are beacons currently removed?

### ISSUE THREAD

**Issue by warrior5230** [ValkyrieofNight/EnvironmentalTech#102]
I tried looking for some sort of change log but couldn't find one so I'm asking here. Have nano beacons been removed? I currently have 1.12.2-2.0.7b installed and I can't find the beacon in the creative menu or anywhere in the config. Sorry if you've already answered this question but I couldn't find an answer on your twitter or anywhere else.

**Comment by PG-Fuury** [comment]
Yes, the beacons have not yet been readded

**Comment by DreamingLamb** [comment]
Can I ask if you're working on them/planning on them returning.  Not trying to ask for an ETA, just if they will ever be back as it's the main thing I'm missing from this amazing mod!

**Comment by zashra00** [comment]
Yes, but rewriting a mod takes a lot of time and work and time so it will just depend on when valk has the time to do it

**Comment by DreamingLamb** [comment]
Understood that it takes time, I've been patiently waiting for months and happy to wait for as long as it takes.  Just wanted to know that they'll be back. :-)

**Comment by ValkyrieofNight** [comment]
Added them in and they will be out in the next release. Hopefully tonight :D
