### ISSUE TITLE
Multiblock dimensional sizes nowhere to be found.

### ISSUE THREAD

**Issue by Labris** [ValkyrieofNight/EnvironmentalTech#105]
Ingame, forums etc. all very well go to detail what blocks and resources are needed for multiblocks. And how many resources do each multiblock generate, it only seems one basic information has been left out from both ingame information or forum posts, what are actual dimensions for each multiblock, kinda causes headache when you need to reserve arbitrary space for tier upgrades

**Comment by CTH999** [comment]
One option for making it visible would be to make it where, when you hover over the controller with your tool, it shows an outline of it. It also shows red where it can't place. I was going to make this suggestion, but then I found this!

**Comment by GrokDuckFarmer** [comment]
The information used to be in the in-game manual, but that's not there any more.  I've been spinning up creative single player worlds to make the multiblock structures since hitting the controller with the tool makes the whole structure.  Not as convenient as the book was.

**Comment by hnOsmium0001** [comment]
left-click the controller block with the assembler wand, you will get the information

**Comment by ValkyrieofNight** [comment]
More information will be coming when the guide is implemented again.

**Comment by ValkyrieofNight** [comment]
Version 2.0.12a contains information in guide
