### ISSUE TITLE
Void Resource Miner has too much Ice

### ISSUE THREAD

**Issue by JonoColwell** [ValkyrieofNight/EnvironmentalTech#108]
The Void Resource miner for some reason lists every variety of Ice as a separate instance of Ice, this leads to about 10.5 pages of Ice varieties and a 37% chance to get ice from your void miner with a clear lens.

See album
https://imgur.com/a/zzTDk 

Mod Version: 2.07b

**Comment by sithrebel15** [comment]
This is not an issue with Environmental Tech. it is an issue with your modpack config and needs to be addressed by the modpack developers.

**Comment by PG-Fuury** [comment]
wym, the void is cold, I see no issues here /s

**Comment by ValkyrieofNight** [comment]
This is a modpack configuration issue. Please report to the modpack dev
