### ISSUE TITLE
Machines could not turn off by redstone signal

### ISSUE THREAD

**Issue by hnOsmium0001** [ValkyrieofNight/EnvironmentalTech#109]
EnvironmentalTech version: **1.12.2-2.0.8b**
_(I don't know why it says 2.0.8a on the file name)_

![](https://i.imgur.com/vvkJfHu.png)
**Without redstone signal**

---

![](https://i.imgur.com/7Zs9why.png)
**Give a redstone signal, break and replace the chest**

**Comment by Hobbler7** [comment]
I can verify this, had to work around it with rftools relays.

**Comment by ValkyrieofNight** [comment]
Will fix.

**Comment by ValkyrieofNight** [comment]
Fixed next release
