### ISSUE TITLE
Void Miner Config (question)

### ISSUE THREAD

**Issue by TheCowKing-moo** [ValkyrieofNight/EnvironmentalTech#110]
Making a modpack that is based around ores only generating in certain biomes. Is there a way to limit the void miners output based on what biome its in?

**Comment by PG-Fuury** [comment]
I don't think there is

**Comment by ValkyrieofNight** [comment]
Not yet but possibly in the future. There is a void miner config overhaul coming soon. Once I get the next new multiblock out I will be working on the void miners.

**Comment by TheCowKing-moo** [comment]
cool beans. thank you.
