### ISSUE TITLE
Void Miners working inside Compact Machines

### ISSUE THREAD

**Issue by silentdragon14** [ValkyrieofNight/EnvironmentalTech#111]
Solar panels work inside the box the mod creates, but i think the miner can't "see" thru the blocks to the void.

**Comment by Xerrass** [comment]
+1

**Comment by thefinaldegree** [comment]
If the miner works how I assume it does, then maybe an option in the config file to have a list of blocks that it considers to be 'bedrock' and if it sees them then it'll activate?

This would allow modpack authors to effectively 'turn on' compatibility for any mod.

**Comment by ValkyrieofNight** [comment]
No longer updating the 1.12.2 version
