### ISSUE TITLE
Void ore miners + Draconic Evolution Wireless Energy Crystals

### ISSUE THREAD

**Issue by StrikzZ** [ValkyrieofNight/EnvironmentalTech#112]
Hey,

I Recently updated my server (FTB Revelation) from 1.6.0 to 1.8.0 which also included an update for ET and Draconic Evolution, i just wanted to report you guys that it was possible to transfer energy to ET machines by hooking it to an Wireless Energy Crystal from Draconic Evolution.
Now after the update it isnt possible anymore, just wanted to point that out.
Dont know if that is intended or even comes from ET or if its another issue.

Just me beeing curious o.o

**Comment by ValkyrieofNight** [comment]
I will take a look into it

**Comment by nullKomplex** [comment]
If it helps the problem isn't DE related. Something changed in the update that messed with RF compatibility. More than DE conduits are broken (I believe Cryostablized Fluxduct was the other thing we tested before just going with RFTools Powercells and/or Mekanism cables) and TOP can no longer see the RF in a controller.

The update that broke it was environmentaltech-1.12.2-2.0.8a.jar. I would normally provide more information to aid you but the changelogs are lacking and the code is close sourced. So hopefully that's enough information.

**Comment by ValkyrieofNight** [comment]
No longer updating the 1.12.2 version
