### ISSUE TITLE
Lonsdaleite is unattainable (no recipe, not generated by void miners)

### ISSUE THREAD

**Issue by AbIntra** [ValkyrieofNight/EnvironmentalTech#113]
modpack:
(FTBRevelation-1.8.0-1.12.2)

mod revision:
(environmentaltech-1.12.2-2.0.9b)

Tested in both multiplayer and singleplayer.
Void miners (all types and tiers) do not generate Lonsdaleite and there does not appear to be any other way to obtain it. This locks away a major feature of Environmental Tech (modifier blocks).

It does not show up in JEI either.
![fn-z](https://user-images.githubusercontent.com/35312627/38066751-fe0570f0-32ce-11e8-8ed2-5bdd8cc70f4b.png)

**Comment by Explosivee** [comment]
Same for me too

**Comment by PG-Fuury** [comment]
I believe modifiers require Mica, not lonsdaleite

**Comment by AbIntra** [comment]
they require both Mica and Lonsdaleite as shown in the image below. All modifier crafting recipes require Lonsdaleite.
![ww2h](https://user-images.githubusercontent.com/35312627/38081504-d1b6be74-3309-11e8-964b-842ffe446c6a.png)

**Comment by ValkyrieofNight** [comment]
This is not a mod issue. This is a pack configuration issue. Please report your bug to the pack devs.
