### ISSUE TITLE
List of ingredients for Void miners too long to list in the chat field

### ISSUE THREAD

**Issue by Robijnvogel** [ValkyrieofNight/EnvironmentalTech#114]
I have, and I am seriously quite bummed about this, lost at least half an hour of my time trying to figure out why my Tier II Void Miner wouldn't form.

Observation:
I hit the block with the Assembler and it neatly listed everything that I needed...
except the **top row**.
I had to actually open my chat in order to see the first line of ingredients: 4 x Null Modifier.
This is a very a-typical thing to be required.

Consideration:
Now this is something that a user will only encounter once, but I am pretty certain that I am not the only one and that there are a lot of annoying questions you can prevent by fixing what in my opinion is a small design flaw.

Proposal:
Change the message, so that it takes up less lines of text. Perhaps list several materials on the same line?
OR
Use a different system for relaying this information to the user.

**Comment by ValkyrieofNight** [comment]
If you open the chat window you can scroll to the others. This will most likely not be changed because the guide will contain these lists also. I will most likely remove the next tier block requirements when the guide contains all the block lists which should help.

**Comment by ValkyrieofNight** [comment]
Version 2.0.12a contains fix
