### ISSUE TITLE
Void Ore Miner Tier 5 not working

### ISSUE THREAD

**Issue by XDLLee** [ValkyrieofNight/EnvironmentalTech#115]
I am currently using EnvironmentalTech 2.09c and ValkyrieLib 2.09b. Since I have only upgraded the ore miner to tier 5, I am not sure if this issue applies to other machines. 
Energy is consumed if the controller is connected to an energy source, but no ore is generated; and the possibility that a certain ore is generated when using ore miner tier 5 is not shown in the JEI.

**Comment by Meryl** [comment]
What is in the configuration files for the void ore miner? It should be in (relative to your minecraft folder) config/environmentaltech/multiblocks/void_miner/ore/tier_5.json

**Comment by XDLLee** [comment]
I deleted the configuration folder and restart the game so it got reconstructed, and everthing seemed to work eventually. I am sorry that I did not backup the folder. 


On 04/05/2018 06:14, Tim wrote:

What is in the configuration files for the void ore miner? It should be in (relative to your minecraft folder) config/environmentaltech/multiblocks/void_miner/ore/tier_5.json

**Comment by ValkyrieofNight** [comment]
It was most likely a misconfigured json. If you have this issue again re-open this issue and post the pastebinned json here.
