### ISSUE TITLE
Config to disable Block Protection? 

### ISSUE THREAD

**Issue by Vyraal1** [ValkyrieofNight/EnvironmentalTech#117]
Is there a way to dismantle a void miner that my teammate set up? Or is there a way to add configs to disable this feature? While it's very thoughtful to have this ability that prevents breaking any blocks of a completed multiblock, it would be nice to disable it for pack devs and players who have pre-existing grief protection such as FTBUtils claiming and etc.

**Comment by Meryl** [comment]
Use the assembler (shift + right click with it in hand) or break the controller first.

**Comment by Xandaros** [comment]
Why is this even on by default, anyway? I'm playing on a private server with a friend and just tried to move the miner he placed. I ended up going into creative to break it - that should not be required...

**Comment by ValkyrieofNight** [comment]
As I said before a config option is coming.

**Comment by ValkyrieofNight** [comment]
Version 2.0.12a contains fix

**Comment by jinkhya** [comment]
Hello, sorry to dig up this but I can't see a config option for it and I'm on environmentaltech-1.12.2-2.0.19.1.jar. what is it called? thanks in advance

**Comment by embermctillhawk** [comment]
> 
> 
> Hello, sorry to dig up this but I can't see a config option for it and I'm on environmentaltech-1.12.2-2.0.19.1.jar. what is it called? thanks in advance

It looks like the config option is in config/valkyrielib/main.cfg

`B:multiblock_protection`
