### ISSUE TITLE
Unable to break void miner

### ISSUE THREAD

**Issue by martmists** [ValkyrieofNight/EnvironmentalTech#118]
On a multiplayers server, a player who was recently kicked out of our FTBUtils team still had their void miner in our base. We cannot tear it down, and even the moderators couldn't do anything about its ownership. Is there any way to remove it?

**Comment by ValkyrieofNight** [comment]
You should be able to break the multiblock fully with the assembler in creative mode.

**Comment by martmists** [comment]
yeah, nobody has access to creative mode :/ Is there really no way to unclaim one from a banned player in survival using only commands?

**Comment by EnigmaticaGH** [comment]
The server admin will have to remove it, most likely

**Comment by ValkyrieofNight** [comment]
Added a removeowner command in next release. Also added a config option to disable protection.

**Comment by ValkyrieofNight** [comment]
Version 2.0.12a contains fix. Use /removeowner while looking at the multiblock controller
