### ISSUE TITLE
saturation buff not applying with the nano bot beacon

### ISSUE THREAD

**Issue by Tsukiumy** [ValkyrieofNight/EnvironmentalTech#12]
i decided to build a tier 1 beacon to facilitate some things arroud my base, setted some buffs, but the saturation is'nt working, as shown in the pic
https://imgur.com/a/Fd72w
as a question related to the beacon, if i add more of one tipe of effect, i get the next tier of it, like if i put 3 strength ones i get strength III?

**Comment by ValkyrieofNight** [comment]
Yeah so right now some modifiers are limited to certain tiers of the nbb for balance reasons. Saturation is tier 3 or above. the default max potion level  1 for tier 1 and tier 2, 2 for tier 3, and 3 for tier 4.

hope this helps :)
