### ISSUE TITLE
1.8.0 Revelation No Lonsdeleite Recipe Still. Uncraftable Modifiers.

### ISSUE THREAD

**Issue by JoeTheSn1per** [ValkyrieofNight/EnvironmentalTech#120]
Recipe only shows a generic block to shard back to block recipe, they don't come from miners, as I have had 4 running for DAYS (real time) now and have gotten 0. And if they do come from miners and I have yet to get a single one, I won't be progressing with the mod any further.

**Comment by ValkyrieofNight** [comment]
This is a pack configuration issue not a mod issue. Report to FTB for a fix. If you want an immediate fix delete the all the files in the "config\environmentaltech\multiblocks\void_miner\ore\" folder.
