### ISSUE TITLE
Parsing error loading recipe environmentaltech:m_resources

### ISSUE THREAD

**Issue by chezpaul** [ValkyrieofNight/EnvironmentalTech#121]
I keep getting these errors in my server log. And I get ZERO environmental tech ores in my world for some reason. 

Running 2.0.9c with 1.12.2 2673 Forge.

Here's my [Log](https://pastebin.com/KpF7UE75)

**Comment by ValkyrieofNight** [comment]
Fill fix.

**Comment by ValkyrieofNight** [comment]
Fixed for next release :P

**Comment by chezpaul** [comment]
👍🏻

**Comment by chezpaul** [comment]
Thanks for the hard work

**Comment by chezpaul** [comment]
How often do you do new releases.  ;-)

**Comment by ValkyrieofNight** [comment]
I was planning on releasing a new update with this fix a little over a week ago but ended up working on the new guide more. Will probably release a bugfix update within the next day or two.

**Comment by chezpaul** [comment]
Cool
Thanks

**Comment by chezpaul** [comment]
Loaded up your updated just now and I get [this error](https://pastebin.com/N3f0Sn6M) when launching server

**Comment by ValkyrieofNight** [comment]
Uploading a fixed version of ValkyrieLib now :P

**Comment by chezpaul** [comment]
It works yeah.. Thanks.
Do you have a retrogen in the config somewhere by any chance?
