### ISSUE TITLE
Lightning Rod outputs random numbers to server console every lightning strike.

### ISSUE THREAD

**Issue by pachexable** [ValkyrieofNight/EnvironmentalTech#122]
Using version 2.0.9b and set up a tier 1 lightning rod in an rftools dimension. Every time lightning strikes the rod, it outputs a random number in the 300k range (im assuming the amount of RF produced) to the server console. 

Unfortunately, it doesn't just output a number to the console to read...it puts it in the bar for typing, meaning it can interfere with server commands. Our server admin had a very interesting time figuring out what was causing it, but it was indeed the lightning rod. Broke it and the issue resolved.

**Comment by ValkyrieofNight** [comment]
Fixed for next release
