### ISSUE TITLE
[1.12.2] Nano bot beacon doesn't work on relog

### ISSUE THREAD

**Issue by P3pp3rF1y** [ValkyrieofNight/EnvironmentalTech#124]
When I log out and log back in to the server nano bot beacon stops working for me. It keeps using power, but no effects work, nor does creative flight. 
Replacing the controller block gets it to work again.
Running Grimco's wasted pack with environmentaltech-1.12.2-2.0.9c.

**Comment by ValkyrieofNight** [comment]
Fixed and will be in next release.

**Comment by MidoriKami** [comment]
I am having the same issue P3pp3rF1y reported, with version environmentaltech-1.12.2-2.0.10a.jar.

On Relog and On Dimension Change the effects stop applying.

I am using Forge's Built in Chunkloader to keep the beacon loaded.

**Comment by ValkyrieofNight** [comment]
Ok I found the bug and have fixed for the next release. Will be avaliable in 2.0.11a

**Comment by MidoriKami** [comment]
Thank you! You are awesome <3
