### ISSUE TITLE
[Suggestion] Name Changes

### ISSUE THREAD

**Issue by X1machinemaker1X** [ValkyrieofNight/EnvironmentalTech#127]
So I realize that people who don't own the environmental tech multiblock cannot break it, but I did not think a minecraft name change would affect that. Turns out it does. Just a suggestion to possible store that by UUID instead of by the players name.

**Comment by ValkyrieofNight** [comment]
The multiblocks do use UUID and not usernames. I will look into why that has happened though.

**Comment by ValkyrieofNight** [comment]
Found the issue :P will have a fix out next release. Possibly in next few days.

**Comment by ValkyrieofNight** [comment]
in current release
