### ISSUE TITLE
[1.12.2] ET mines and provides Untextured and wrong NBT damage value for Draconium Dust

### ISSUE THREAD

**Issue by Morpheus1101** [ValkyrieofNight/EnvironmentalTech#128]
When using the Void miners the draconium dust thats mined is untextured an has the wildcard dmg value of 32767 and also has the incorrect ID # compared to what is ingame as seen by the below pictures.

ET v2.0.9c
ValkLib v2.0.9b
Forge *.2687

![2018-05-20_19 51 31](https://user-images.githubusercontent.com/10524952/40277710-566faadc-5c67-11e8-9e0b-7e2cec1720bf.png)
![2018-05-20_19 46 01](https://user-images.githubusercontent.com/10524952/40277711-57cdaf00-5c67-11e8-917d-0d1a1fb23c7e.png)

**Comment by MidoriKami** [comment]
See #103
