### ISSUE TITLE
Void Resource Miner Isn't working.

### ISSUE THREAD

**Issue by doctor-nick** [ValkyrieofNight/EnvironmentalTech#129]
Hey, I've been bouncing around all over the internet trying to find information about this, but there diesn't appear to be anything. I've got the resource miner setup next to an ore miner with the exact same configuration but the resource miner doesn't seem to be working.
I'm running FTB Continuum version 1.0.1, on the Twitch launcher if that helps.

![](https://i.imgur.com/1UwwmZ1.png)
If you look closely, you can see an item travelling through the pipe. The ore miner is working normally.
![](https://i.imgur.com/hDOtem6.png)
The resource miner is configured the same way, sans torch on the side, which I doubt is the problem.

Haven't tried with other tiers, but I found a hungarian video explaining the resource miners in 1.12, and [he appears to have the same problem](https://www.youtube.com/watch?v=DpXfmlZKa8g)

**Comment by wbayer81** [comment]
Couldn't get it working with Ender IO Conduits. Wasn't Mining at all.
I replaced the Conduits with a Dimensional Transceiver and it started to mine resources.

**Comment by ValkyrieofNight** [comment]
Its most likely an error in the json file in your configs. Other than that it works perfectly fine in the tests that ive done to try and replicate this bug.
