### ISSUE TITLE
Feature Request: Redstone sensitivity

### ISSUE THREAD

**Issue by GrokDuckFarmer** [ValkyrieofNight/EnvironmentalTech#13]
I would love the nano bot beacons to be affected by redstone:

1. A redstone signal applied to the beacon itself disables the beacon.
2. A redstone signal applied to a modifier block disables that modifier while keeping the rest active.

I love night vision, but occasionally I want it off while viewing how something is lit up, or when the bright red of the Nether is too oppressive.  With chat detectors, it's possible to issue a command in-game that would turn on/off the redstone signal remotely.

**Comment by ValkyrieofNight** [comment]
Great suggestion! I will add that to my todo list.

**Comment by ValkyrieofNight** [comment]
All multiblocks can be disabled with a redstone signal applied directly to the controller. I will add per modifier at some point in the future.

**Comment by ValkyrieofNight** [comment]
My bad should keep this open.
