### ISSUE TITLE
Health Boost hearts can't be filled

### ISSUE THREAD

**Issue by Yadokingu** [ValkyrieofNight/EnvironmentalTech#130]
environmentaltech-1.12.2-2.0.10a
forge-14.23.4.2705

The Nano bot beacons health boost creates the extra hearts, but they can't be filled. Half a heart fills, but gets drained right away. A lot of saturation is consumed in the process.

**Comment by ValkyrieofNight** [comment]
The Health Boost modifier is not complete that is why it does not have a recipe.

**Comment by ValkyrieofNight** [comment]
added
