### ISSUE TITLE
[1.12.2] lonsdaleite Unobtainable

### ISSUE THREAD

**Issue by Morpheus1101** [ValkyrieofNight/EnvironmentalTech#136]
Forge *.3.2705
ET v2.0.11a

i've got multiple T4 Void Resource and Ore miners and after going through the tier*.json files i found no trace what so ever of any of them having the lonsdaleite crystal available to be gathered and yet we are using default configs in this pack and it is an item required to be able to get different modifier's but currently has no way in which to obtain said resource...How do we obtain this crystal short of manually adding it into the list of tiers manually ourselves ?

**Comment by Meryl** [comment]
Did you let the most recent version (re)generate the json files? You can temporarily move the files somewhere else and then try starting the game, it should generate the correct files.

**Comment by Morpheus1101** [comment]
No i hadnt, but that indeed does fix the issue.
