### ISSUE TITLE
[1.12.2]-- [main/ERROR] [FML]: Could not load vanilla model parent ...

### ISSUE THREAD

**Issue by Fatmice** [ValkyrieofNight/EnvironmentalTech#139]
forge-14.23.4.2705
environmentaltech-1.12.2-2.0.10a
valkyriecompat-1.12.2-2.0.10a
valkyrielib-1.12.2-2.0.10b

https://gist.github.com/Fatmice/aab927e819bef1cc9cc384f267dafecd

**Comment by Meryl** [comment]
Did you try upgrading to the most recent version of ET, ValkyrieCompat and ValkyrieLib?

**Comment by Fatmice** [comment]
The error messages are still there in the latest
environmentaltech-1.12.2-2.0.11a
etlunar-1.12.2-2.0.11a
valkyriecompat-1.12.2-2.0.11a
valkyrielib-1.12.2-2.0.11a

https://gist.github.com/Fatmice/b231dd0bddbb0733c20f786b49c00b47

**Comment by ValkyrieofNight** [comment]
No longer updating the 1.12.2 version
