### ISSUE TITLE
Feature request: slightly faster buff from nano bot beacon

### ISSUE THREAD

**Issue by GrokDuckFarmer** [ValkyrieofNight/EnvironmentalTech#14]
It appears that the buff from the nano bot beacon it applied and renewed every few seconds.  Normally this isn't an issue, but on a server that is running a bit laggy, the night vision buff can drop low enough that the flashing visual indication that the night vision effect is wearing off can be seen.  It would be nicer to reapply the nano bot beacon buffs faster, or in such a way that the flashing visual indication doesn't occur unless the nano bot beacon is turned off.

**Comment by ValkyrieofNight** [comment]
Will do!
