### ISSUE TITLE
assembler dupes at deconstruction

### ISSUE THREAD

**Issue by purplemonday** [ValkyrieofNight/EnvironmentalTech#141]
enviroment Multiplay/sponge
version: latest

with a lower tps occasonaly blocks get droped multiple times using the assembler to deconstruct it.

ended up with multiple dupe lenses and controllers this way.
ocurance is rare and hard to duplicate in singelplayer but happends more in (full) multiplay server

**Comment by ValkyrieofNight** [comment]
Usually dupe bugs when running sponge are caused by sponge. The assembler uses vanillas break block code so that would be a bug with sponge.
