### ISSUE TITLE
Erodium Crystal not spawning

### ISSUE THREAD

**Issue by Pigbull320** [ValkyrieofNight/EnvironmentalTech#142]
i have the miner working but so far its just an ice machine.. after hours not a single one. The miner has mined over 800 blocks and jei says it has a 1.5% chance. so i should have around 12 by now.. i can't make the crystal lens until i get erodium so im at a loss... 5 stacks of ice is the majority. i know this is an old issue but beyond making 9 more miners and wait another 6ish hours and hope i get 1. i just downloaded the mod today so i see no reason to update the files like you suggested others to do in the past. thank you.

**Comment by DieselDuk** [comment]
Sounds like you are using a resource miner whereas you should be using an ore miner.

**Comment by ValkyrieofNight** [comment]
You are using the resource miner. You will need to use the Void Ore Miner in order to get erodium.
