### ISSUE TITLE
[1.12.2] Client crash pressing U on glowstone blocks in your inventory

### ISSUE THREAD

**Issue by b0bst3r** [ValkyrieofNight/EnvironmentalTech#144]
environmentaltech-2.0.12a.jar
forge 14.23.4.2705

Having a glowstone block in your inventory and hovering mouse cursor over it and pressing U for uses causing the below crash.

https://pastebin.ubuntu.com/p/sndsBzNtKy/

I spoke to the EnderIO devs and they said to post it here as it's an issue with ET.

**Comment by ValkyrieofNight** [comment]
Ok It looks like I have fixed the bug in my dev environment. Will have the update out soon :P
