### ISSUE TITLE
All multiblocks lost 'owner', can no longer break any ET multiblock

### ISSUE THREAD

**Issue by Matakor** [ValkyrieofNight/EnvironmentalTech#147]
https://i.imgur.com/1cba0qj.png

I can't break my own multiblocks..
On personal server, latest versions of mods/forge/etc.

Shift+rightclick with assembler does nothing, trying to break with other tools does not work, etc. 

Is there a way to remove assignment to allow me to actually break the multiblock?

**Comment by Matakor** [comment]
Side note: Mekanism cardboard boxes can be used to wipe ownership of multiblocks, allowing individuals to reassign multiblock ownership.

**Comment by CharCharthemonkey** [comment]
i have a similar issue the only way i could fix was by going gamemode 1 and breaking the controllers and cheating them back in
![2018-08-18_16 28 24](https://user-images.githubusercontent.com/30783285/44304993-2e94dc00-a332-11e8-8851-198d20e77971.png)

**Comment by ValkyrieofNight** [comment]
Fix coming tonight. Sorry about that peeps. Owner system has been changed :P
