### ISSUE TITLE
BUG: Multiblocks missing after update + server console log spam

### ISSUE THREAD

**Issue by jerry1333** [ValkyrieofNight/EnvironmentalTech#148]
Hi,
I've updated all 3 mods to latest versions:
- EnvironmentalTech from 1.12.2-2.0.13a to 1.12.2-2.0.15a
- ET Lunar from 1.12.2-2.0.13a to 1.12.2-2.0.15a
- valkyrielib from 1.12.2-2.0.13a to 1.12.2-2.0.15a

Server is starting, game too but server reports error from TileEntity:
https://pastebin.com/7SLBNqdk

Reverting to 13a cause them to work fine. 
If I copy world to local computer and start single player it's working fine even in 15a.

Thanks for any advice or fix.

[debug.log](https://github.com/ValkyrieofNight/EnvironmentalTech/files/2300146/debug.log)
[latest.log](https://github.com/ValkyrieofNight/EnvironmentalTech/files/2300147/latest.log)

**Comment by jerry1333** [comment]
Had to remove all multiblocks from world in 13a and then update to 15a to get it working. Looks like some NBT data changed?

**Comment by ValkyrieofNight** [comment]
Woops will have a fix out later today
