### ISSUE TITLE
[suggestion] hidden particles enhancement for nanobot beacon

### ISSUE THREAD

**Issue by shadoxxhd** [ValkyrieofNight/EnvironmentalTech#149]
It would be nice if there was a modifier that changed all active status effects to hide their particles. Ideally this would extend to non-ET status effects (nanobots eating up the particle renderer), but it's most important for the beacon effects since they are supposed to be always active once you can afford the multiblock/energy for it.

**Comment by ValkyrieofNight** [comment]
The modifiers don't have particles enabled. I purposely disabled the particles for my nanobot beacons because I don't like them in my face when I play.

**Comment by shadoxxhd** [comment]
I had particles spawning when I first built the beacon, but after restarting minecraft have not seen thiem since...
Probably was some strange mod interaction. If I see particles again, I'll investigate closer and reopen this if necessary.
