### ISSUE TITLE
[HUGE SUGGESTION]

### ISSUE THREAD

**Issue by Gazzzaa** [ValkyrieofNight/EnvironmentalTech#152]
So with the botanic miner and modpacks you will get roughly around 600 different types of leaves which is very unnecessary, if we could easily change this in the configs we would but it seems with your mod it is either "all default" or "all custom" which is very irratating for modpack devs. So I would suggest that the config and mod compatability options to be worked on for people to customize there packs a lot easier. @

**Comment by ValkyrieofNight** [comment]
There is a json with all the stuff in it and its super simple...
