### ISSUE TITLE
[1.12.2] Forge Crashes While Loading (Phase 1/7)

### ISSUE THREAD

**Issue by PulseBeat02** [ValkyrieofNight/EnvironmentalTech#156]
Hi, I have been recently been loading my big modpack into Minecraft Forge, but it has crashed with an error in phase 1/7. 

Minecraft Version: 1.12.2
Environmental Tech Version: 1.12.2-2.0.16.1
Forge Version: 14.23.4.2765

Here is the crash report: https://paste.dimdev.org/yojecizori.mccrash

Anyone know what is going on?

**Comment by ValkyrieofNight** [comment]
Looks like you will need to update Environmental Tech to 1.16.1 also. But now that there are 1.17.x versions out you should use them :P

**Comment by ValkyrieofNight** [comment]
Oh and I saw that version in the log I know you said you were running 16.1 but the log says 15.1
