### ISSUE TITLE
[1.12.2]Break and Drop NOTHING

### ISSUE THREAD

**Issue by 5huxiaoyang6** [ValkyrieofNight/EnvironmentalTech#157]
ValkyrieLib Version:  2.0.17.1(ingame display.And I'm sure using the latest version download from Curse. )
Environmental Tech Version:2.0.16.1(The same problem as above.The file name seems don't fit the mod's version)
Description of bug:When I broke the  structure frame blocks from the machine with a pick ,I found it drop nothing.And later I tried breaking them with assembler tool,causing the same case.

**Comment by ValkyrieofNight** [comment]
Youll need to update Environmental Tech to 2.0.17.1

**Comment by Gamertech** [comment]
ValkyrieLib: 2.0.17.2
E-tech: 2.0.17.1
E-mats: 1.0.17.2

Getting the same. Breaking a structure block for example with an assembler or a pick will destroy the block, not drop it.

Downgrading to 2.0.15.1 fixes the issue.

**Comment by ValkyrieofNight** [comment]
Ok will try get a fix out tonight.

**Comment by ValkyrieofNight** [comment]
Fixed in new release: 2.0.17.3

**Comment by ValkyrieofNight** [comment]
That is for ValkyrieLib sorry forgot to mention that haha

**Comment by Gamertech** [comment]
Can confirm blocks drop as intended with the new ValkyrieLib. Cheers :)
