### ISSUE TITLE
Does the Void Ore Miners and Solars chunkload?

### ISSUE THREAD

**Issue by Shybella** [ValkyrieofNight/EnvironmentalTech#158]
Does that happen?

Thanks

**Comment by ValkyrieofNight** [comment]
Nope they don't chunkload themselves.... yet :P

**Comment by Shybella** [comment]
They do chunkload, I just tested this now.

Teir 6 Void Ore Miners.

**Comment by ValkyrieofNight** [comment]
They do not chunkload.
