### ISSUE TITLE
Feature Request: Walls of all the building blocks

### ISSUE THREAD

**Issue by leojaxx** [ValkyrieofNight/EnvironmentalTech#16]
Hey man, love the mod. Love the ore miners, love the building blocks. Alabaster is <3
I was actually just looking to fork the mod so I can add the walls in myself then give you a pull request, but looks closed source so I'm asking that maybe you can add them when you have a chance? Right now I'm making walls with chisels and bits lol.
If you don't have time or whatever to add them is it ok if I make my own mod that's an addon to this adding the walls?
Thanks. Love this and the generators.

**Comment by ValkyrieofNight** [comment]
Yeah sure I will add them in. Will add that to my todo list.

**Comment by ValkyrieofNight** [comment]
I do not have time to add these unfortunately. Feel free to make an addon if you wish.
