### ISSUE TITLE
blocks outside of the controller arent harvestable

### ISSUE THREAD

**Issue by CharCharthemonkey** [ValkyrieofNight/EnvironmentalTech#160]
no matter wat block it is outside of the controller they are not havrestable and just vanish when they are tried to be harvested (like breaking blocks in creative) but in survival mode 

version 1.12.2 2.0.17.1 for enviromental tech and lunar and it does it for both mods

**Comment by ValkyrieofNight** [comment]
Make sure ValkyrieLib is on 1.12.2-2.0.17.3

**Comment by CharCharthemonkey** [comment]
ok ill try that thank you tho i checked and last time there wasnt an update for it

**Comment by AndrewTru** [comment]
I can say that I myself am using that version and some of the blocks if I try to mine them with the assembler will hide and not technically get removed, this is starting to become a invisible block event.
I am still trying to find a tree that I 'hid' and not run into and I have bumped into it a lot.

**Comment by CharCharthemonkey** [comment]
i updated as Valkyrie said and now the blocks are breakable again sotry updating @AndrewTru and see if that works

**Comment by CharCharthemonkey** [comment]
umm to update all u have to do us unlock the pack update the mod and ure good @AndrewTru

**Comment by AndrewTru** [comment]
If it was a public mod pack yes, but I am having that issue in a private pack.
I even checked what version I have and it still happens so unless there is an update that twitch is not seeing or an Alpha I can point to I don't see why this issue is so 'oh it's just that version can you update to this version'.

**Comment by ValkyrieofNight** [comment]
The pack developer needs to update the mod. Alternatively you can unlock the pack in profile options and then update it yourself. The latest version does not have this issue.
