### ISSUE TITLE
Multiblocks dont complete themselves even with the assembler

### ISSUE THREAD

**Issue by Algester** [ValkyrieofNight/EnvironmentalTech#161]
Apparently from my stoneblock experience the multiblock forgets to check the player inventory for all the items which results in missing blocks that require the player to place them manually either this may have something to do with inventory sorting mods maybe...

**Comment by ValkyrieofNight** [comment]
Check to make sure you don't have any blocks in the way of it constructing.

**Comment by Algester** [comment]
I would believe that was the case but I had enough space for the multiblocks doesnt seem to happen so much if the multiblock was placed in a total void world

Even without the arcane lantern from thaumcraft it still happens just how big of a space does the assembler check? Since I’m building most of the multiblocks in Stoneblock

**Comment by BecksIsAlreadyTaken** [comment]
the same problem

the assembler only build a small part of the whole multiblock structure and then it wont react no matter how you right-click the void miner

**Comment by IamStig** [comment]
I have a similar issue, testing on a new pack that Slowpoke101 is working on. I know this is a mod issue but ....the environmental tech personal nano. It failed to form correctly, 3 blocks not placed, 1 block was reasonably obvious..it was a frame block around the bottom edge, but the 2 other blocks were not, they were under 2 of the modifier blocks. this structure is not just black it has been created to not increase brightness even with a torch on it. It took about an hour trying to find the last 2 block positions, rebuilding 3 times and I only found the missing blocks when I removed the null modifiers to replace them and saw light under 2 of them. The structure was build above a new platform in a void world with no chance any "blocks" could have been stopping the placement of the missing blocks

**Comment by BecksIsAlreadyTaken** [comment]
I changed to aroma's dimension and it worked

**Comment by IamStig** [comment]
Not sure if your saying you moved it to the aroma dimension or you visited the aroma dim. If you visited and returned and the structure formed I would imaging that relogging would also work (that was something I considered but did not try) If your saying you moved the structure to the aroma dim then that is only a fix/workaround for you. In my case I don't have an option to move to another dimension so an actual fix or even blocks that allow you to SEE the block instead of a wall of black

**Comment by BecksIsAlreadyTaken** [comment]
I mean i moved all the stuff to aroma world(built the environmental tech machine there). Maybe it's because there is no any other ore in Stoneblock main world. Also i didnt encounter the light issue so probably it's not the same problem

**Comment by ValkyrieofNight** [comment]
No longer updating the 1.12.2 version
