### ISSUE TITLE
T1 Void Ore Minder Not Working

### ISSUE THREAD

**Issue by ErAgOn8182** [ValkyrieofNight/EnvironmentalTech#165]
The laser to my VOM will not start up. Using newest version of Direwolf20 1.12 pack. I've checked the FTB diagram, and I built the object with the assembler using all the listed blocks in chat. Structure does not complete, and laser does not form. There is a hole to bedrock that is completely unobstructed.

**Comment by Algester** [comment]
that means its an incomplete structure it happens in my playthrough of stoneblock as well check the sides for any missing blocks

**Comment by Kiefy** [comment]
I find that Cave Illuminator's are a common blocker of auto formation, or the Tinker's light globs.

Make sure the area is nothing but air.
