### ISSUE TITLE
Void Miners Tick Acceleration

### ISSUE THREAD

**Issue by oleg333l** [ValkyrieofNight/EnvironmentalTech#166]
Void Miners seems to not react at tick accelerators(torcherino, acceleration wand, watch of flowing time), tested with creative energy sourse. Is it intended or am I doing it wrong?
![2018-11-29_18 19 41](https://user-images.githubusercontent.com/8050905/49246427-8fe24600-f41d-11e8-9ec7-642b298f8739.png)
Forge version:14.23.5.2768
ET/LIB version: from 2.0.15.1 to 2.0.18.2
Other mods:
![image](https://user-images.githubusercontent.com/8050905/49246288-2feb9f80-f41d-11e8-81f2-b376da9aaa36.png)
Latest log: https://pastebin.com/CukRhgyX

**Comment by Algester** [comment]
I think the update broke it whether or not thats intentional I dunno it did worked prior no wonder....

**Comment by FuuNoKamiOka** [comment]
Just gonna point out it's been another month and no fix.

(Add on: Mod maker said on Twitter that his net was cut off on the 11th of Dec. That might factor into it.)

**Comment by Shybella** [comment]
It should be left broken as it becomes broken when you use these acceleration tools with environmental tech.

**Comment by DemonfangArun** [comment]
This should not be a thing anyway, if you want them faster use the speed upgrades as intended. This mod doesn't really need speed upgrades, and I wouldn't mind seeing it coded against them.

**Comment by ValkyrieofNight** [comment]
This is not a bug. I disabled tick acceleration on purpose because it is stupidly op. The fact that you could do it in a few previous versions was actually a bug.

**Comment by Kiefy** [comment]
I recently saw someone on a stream go through all the trouble of setting up an Astral Sorcery time crystal to speed up their void miner. for it to then have 0 effect is just heartbreaking and anti-fun.

If you become a wizard and master the power of time. nothing should stand in your way.

**Comment by icedsdcard** [comment]
I think there should be a note in the guide that they cannot be tick-accelerated.
Perhaps the assembler should have a tooltip about it.
(Particularly nice for players who are switching from one mod to the next in a 500-mod progression pack - which, I think, is bad pack design, but some bad pack design is to be anticipated.)
(Having a tooltip on every machine might feel repetitive, too up-front, and "loud".)

**Comment by ProxyPlayerHD** [comment]
to be honest why not just make it an option in the config to enable tick acceleration?

it's a win-win for everyone.

**Comment by FuuNoKamiOka** [comment]
So, I'll be honest, I made my comment before I started using the mod's version of speed upgrades and HOT DANG ya'll. They work well. Just use the speed upgrades and you'll be fine.

**Comment by ProxyPlayerHD** [comment]
the Speed modifer requires materials i get from machines i want to speed up in the first place to get those materials

it's a catch 22

**Comment by MuteTiefling** [comment]
> just getting enough erodium to make a lens to get more erodium is a pain to do. you either need a lot of miners or a lot of time.

I usually start with about 6 tier one miners to get past the early hump, then use those structure blocks to build progressively fewer of the high tier miners. Works out fine. You're going to need the structure blocks eventually anyway, so you may as well use them early on.
