### ISSUE TITLE
Bug: assorted issues in default configuration

### ISSUE THREAD

**Issue by LemADEC** [ValkyrieofNight/EnvironmentalTech#168]
As of 1.12.2-0.18.2, the default configuration for Void ore mining are suffering various issues.

First and most importantly, Thaumcraft entries are giving the crystal blocks instead of the vis item. In the related mod, Crystal block can only be obtained from mid-game crafting as mining would only give the Vis Crystal item form. The latest requires NBT data, for example with Aqua in CraftTweaker notation, that would be:
<thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "aqua"}]})
Nota: you can convert an NBT string to actual NBT with something like that:
```
try {
	final NBTTagCompound tagCompound = JsonToNBT.getTagFromJson(stringNBT);
	itemStack.setTagCompound(tagCompound);
} catch (final NBTException exception) {
	xxx
}
```

Second, "OD:oreBrainstone" is defined twice.

Last, in the tier1, EnvironmentalTech entries are at the end of the file while other tiers have it at the beginning. Consistent position helps modpack authors to configuration progression.

**Comment by ValkyrieofNight** [comment]
No longer updating the 1.12.2 version
