### ISSUE TITLE
Ore miner mining the wrong crystals

### ISSUE THREAD

**Issue by DemonfangArun** [ValkyrieofNight/EnvironmentalTech#169]
As a followup to #133, the ore miner is outputting the wrong item. The crystals that the miner is giving are meant to be crafted in thaumcraft as part of the progression, having a machine create them is detrimental to the immersion. The output item (and the proper drop when mined) is vis crystals (thaumcraft:crystal_essence) with the appropriate nbt data.

**Comment by Techno-Turnovers** [comment]
You could argue this with every mod; you could always just blacklist Vis crystals in the config, if it bothers you.

**Comment by ValkyrieofNight** [comment]
No longer updating the 1.12.2 version
