### ISSUE TITLE
Void miners going too fast

### ISSUE THREAD

**Issue by DemonfangArun** [ValkyrieofNight/EnvironmentalTech#171]
In the config I changed the energy duration to 10% of default, but the void miners seem to be running at 5x normal sped after doing this. My intent was to lower both the energy usage to 10% of default, but keep the default speed. I'm not sure what governs this, but it appears that adding a manual control for the ore miner speed is going to be needed.

**Comment by ValkyrieofNight** [comment]
No longer updating the 1.12.2 version. This is also configurable in the 1.16.4 version.
