### ISSUE TITLE
BUG: Disabling Ranged Beacon removes Personal recipe

### ISSUE THREAD

**Issue by Gamertech** [ValkyrieofNight/EnvironmentalTech#173]
ValkyrieLib Version: 2.0.19.1
Environmental Tech Version: 2.0.19.1

Description of bug: Disabling the ranged beacon in the ET config successfully removes the ranged beacon controllers, but also removes the recipe for the tier 1 personal beacon controller.

Tier 2+ controllers all have recipes as intended.

**Comment by ValkyrieofNight** [comment]
1.12.2 version no longer supported.
