### ISSUE TITLE
BUG: OD_PREFIX in void miner configs only work for items if ALL entries of ore dictionary for the item are defined

### ISSUE THREAD

**Issue by Minerdomera** [ValkyrieofNight/EnvironmentalTech#174]
ValkyrieLib Version: 2.0.19.1

Environmental Tech Version: 2.0.19.1

Description of bug: If an ore dictionary entry in the void miner config is used, it will only work on items that ONLY have that entry; If the item has multiple entries (for example, seeds have the entries seedWheat, ListAllSeed, seed, and ListAllseed) the item will only be added if ALL of the entries are added to the config.

How to reproduce bug:  Add an OD_PREFIX entry for an item that has more than one ore dictionary entry to one of the void miner configs.
Example:
{
      "target": "seed",
      "weight": 16,
      "id": "OD_PREFIX:listAllSeed"
}
Items that match ONLY listAllSeed will be added to the void miner, but none that have any other entries that are not entered into the config file.

**Comment by ValkyrieofNight** [comment]
1.12.2 version no longer supported.
