### ISSUE TITLE
BUG: If OD_PREFIX is used to add an item to the void miner configs, it will also add any items that share a data value with an item with that ore dictionary entry

### ISSUE THREAD

**Issue by Minerdomera** [ValkyrieofNight/EnvironmentalTech#175]
ValkyrieLib Version: 2.0.19.1

Environmental Tech Version: 2.0.19.1

Description of bug: If an item is added using OD_PREFIX in the void miner config, items that share the same data value of an item with that ore dictionary entry will also be added to the void miner. As many mods tend to have items that share a data value and instead have a large amount of metadata subtypes (for example, modname:material:26), this can cause many unintended items to be added to the void miner.

How to reproduce bug:  Add an OD_PREFIX entry for an item that shares it's data value with multiple items, but do not share the same ore dictionary entry (vanilla items tend not to do this, so another mod may be needed to reproduce, any mod that uses a large amount of items that share the same data value may do, like Actually Additions, Thermal Foundation, etc.). for example, using Natura, adding "OD_PREFIX:crop" would add Barley, fruit and other crops, but would also add all the other items that share the same data value as them(Imp leather, flamestring, etc).

**Comment by ValkyrieofNight** [comment]
1.12.2 version no longer supported.
