### ISSUE TITLE
Railcraft sulfur ore

### ISSUE THREAD

**Issue by DemonfangArun** [ValkyrieofNight/EnvironmentalTech#177]
The ore miner seems to be picking this up with a broken texture. ~Railcraft doesn't even have any sulfur anything in it.~ It seems that something else is being broken, further testing is needed...

**Comment by liach** [comment]
Railcraft does have sulfur.

**Comment by DemonfangArun** [comment]
> 
> 
> Railcraft does have sulfur.

-searches config to double check- well ok then, jei doesn't list it, despite it being enabled in the config. Since I already have sulfur from thermal expansion, I'll just disable the railcraft one to see if that has an effect. I'll leave this open since regardless there's still an issue.

**Comment by ValkyrieofNight** [comment]
No longer updating the 1.12.2 version
