### ISSUE TITLE
BUG: NullPointerException with guide

### ISSUE THREAD

**Issue by Gamertech** [ValkyrieofNight/EnvironmentalTech#186]
ValkyrieLib Version: 1.12.2-2.0.20.1
Environmental Tech Version: 1.12.2-2.0.20.1

Description of bug: It doesn't seem to be negatively affecting anything, but this error is showing in the logs pointing to the guide while loading a pack.

Log: https://pastebin.com/hfvcj0B4

(If Applicable)Modpack Name: Chaotic Progression 1.3.4

How to reproduce bug: Error is generated during initial pack load.

**Comment by ValkyrieofNight** [comment]
1.12.2 version no longer supported.
