### ISSUE TITLE
Lightning rod requires close proximity

### ISSUE THREAD

**Issue by karlzoller** [ValkyrieofNight/EnvironmentalTech#190]
Lightning rod does not seem to work when not standing quite close to it. For example. when I am 50 blocks away I can wait for 10+ minutes with no strikes. When I walk up to it I get one withing 3 min. This happens quite consistently.

**Comment by ValkyrieofNight** [comment]
Chunk load it. There is no system in the multiblock that detects weather the player is close by. Also it is not a fixed duration for strikes it is a range of time. Look in the Digital Guide found in ValkyrieLib for more details.
