### ISSUE TITLE
Typo in solar panel tier 3 block requirements

### ISSUE THREAD

**Issue by Solarcis** [ValkyrieofNight/EnvironmentalTech#193]
Quite simple, actually. I was trying to use an assembler to create the structure for a tier 3 solar panel. It only claimed I needed 8 null modifiers, so I had 8 in my inventory. What resulted after using the assembler was a bit of confusion until I noticed what looked like more null modifiers were missing+needed, judging by the asymmetry that only 8 blocks made. Apparently it needed 12. I thought I'd report this. Thanks!

**Comment by ValkyrieofNight** [comment]
These block requirement values are generated from the structure itself so they are not wrong. The tier 3 solar array only requires 8 modifiers total.
