### ISSUE TITLE
No void to point at

### ISSUE THREAD

**Issue by Techno-Turnovers** [ValkyrieofNight/EnvironmentalTech#195]
I use a mod called Cubic Chunks (1.12.2), which allows for infinite world height and generation by replacing chunks with 16x16x16 cubes. One consequence of this is that no void, or even bedrock, spawns in the world, meaning that the Void Ore Miner and Void Resource Miner both do not work. If there could be some sort of config to disable the seeing void requirement, that would be good, since my understanding is that every other multiblock without this requirement works fine.

**Comment by ValkyrieofNight** [comment]
Did you test this? Because it should work as long as you have a clear line of sight to y-level 0

**Comment by Techno-Turnovers** [comment]
Tested; it doesn't work, even if the structure is built outright below y=0.

**Comment by Techno-Turnovers** [comment]
Wait, i'm stupid, it works.

**Comment by Techno-Turnovers** [comment]
To clarify: I was actually reading someone else's compatibility report, but I looked again and they were doing it wrong. XP
