### ISSUE TITLE
Crystal Ores, no texture and no apparent usage.

### ISSUE THREAD

**Issue by llloyd4** [ValkyrieofNight/EnvironmentalTech#197]
So, this is for 1.12.2. I installed ET 3 days ago, built a Tier 1 Ore Miner, and left it to run non stop for the long hours I play a day in my world, and only got like 16 Erodium crystals. As it takes 6 blocks of Erodium to make a crystal lens, yeah... Seeing this is re-donk-ulously slow I poked at the configuration file to see if there is an easy mode. No easy mode switch, unfortunately, but I did see an ore setting for the other crystals. So I set them all to true, poked at JEI, and see that they have no textures and no usage according to JEI. So... Yeah...  :(

**Comment by ValkyrieofNight** [comment]
The ores are disabled by default because they are unfinished soooo don't enable them...

There is a loot table in the config where you can change the rate at which any ore is mined so no need for an easy mode. config\environmentaltech\multiblocks\void_miner\ore\
