### ISSUE TITLE
1.11.2 Console spam 100mb logfile.

### ISSUE THREAD

**Issue by ProsperCraft** [ValkyrieofNight/EnvironmentalTech#20]
java.lang.IllegalAccessException: Class com.valkyrieofnight.valkyrielib.multiblock.block.VLBlockSlave can not access a member of class com.valkyrieofnight.environmentaltech.init.ETBlocks$1LRI_SLAVE with modifiers ""

Find attached zip file containing the 107mb logfiles(zips to 1.4megs)

[consolespamlogs.zip](https://github.com/ValkyrieofNight/EnvironmentalTech/files/720019/consolespamlogs.zip)

Version- environmentaltech-1.11.2-0.11.0b

The console has become unresponsive due to the massive amount of scroll.

**Comment by ProsperCraft** [comment]
![starky](https://cloud.githubusercontent.com/assets/4427684/22167180/fb420eca-df21-11e6-9b3a-746ab8018c70.png)

Picture of the setup.

**Comment by ValkyrieofNight** [comment]
Thanks will fix!

**Comment by ValkyrieofNight** [comment]
Fixed and latest build.
