### ISSUE TITLE
Building EV miners crashes world

### ISSUE THREAD

**Issue by blace2121** [ValkyrieofNight/EnvironmentalTech#201]
I'm playing on MC eternal. Added ET and whenever I try to build any of the machines with the assembler the game crashes. It lists as possible reasons Environmental tech, Valkyrie lib, reskillable, or universal modifiers, but I have made sure all are up to date, and I got nothing.. For whatever reason hitting a controller with the assembler once works,  but the second hit always crashes. Would love some help, this is an awesome mod!

**Comment by ValkyrieofNight** [comment]
1.12.2 version no longer being worked on.
