### ISSUE TITLE
Maybye a question

### ISSUE THREAD

**Issue by PatriikPlays** [ValkyrieofNight/EnvironmentalTech#203]
Friend cant access my void ore miner(breaking things)
Were playing on a multiplayer server and uhh you might anwser wait for him but its an issue if we have diff timezones so when its like 10Am for me for him its like 1AM so yeah and waiting 7 hours isnt fun so any commands or something?

**Comment by ValkyrieofNight** [comment]
1.12.2 version no longer supported.
