### ISSUE TITLE
BUG: [1.12.2] Error when ?right clicking enviromental tech's blocks? 

### ISSUE THREAD

**Issue by Miner28** [ValkyrieofNight/EnvironmentalTech#204]
Hello we are having problem when someone click enviromental tech's blocks mosty happens on controller but other blocks does that too.. But what is weird that it does happen only sometimes
Crash log: https://hastebin.com/iyemaqahib.rb
Seems like confict with some mods

**Comment by Miner28** [comment]
Is this github dead ?

**Comment by ValkyrieofNight** [comment]
1.12.2 version no longer being worked on.
