### ISSUE TITLE
Typo in Digital Guide "Resourse"

### ISSUE THREAD

**Issue by Ricket** [ValkyrieofNight/EnvironmentalTech#209]
The headers in the void resource miner section of the digital guide have a typo of the word resource.

![image](https://user-images.githubusercontent.com/196978/89715940-f350a500-d96e-11ea-9c10-b190d44a30b6.png)

environmentaltech-1.12.2-2.0.20.1

**Comment by ValkyrieofNight** [comment]
1.12.2 version no longer being worked on.
