### ISSUE TITLE
Envirocore needed, but can't find that mod

### ISSUE THREAD

**Issue by BigAl607** [ValkyrieofNight/EnvironmentalTech#213]
I just recently added EnvironmentalTech 1.16.4-3.0.4.0 and ValkyrieLib 1.16.4-3.0.4.1 to a pack I put together. When I launched the game, I get the error message below show up.

![enviro](https://user-images.githubusercontent.com/13182567/100180283-d13f4c00-2ea5-11eb-809f-f4db9fcf8b79.png)

Problem is, I can't find Envirocore anywhere. Any suggestioins?

**Comment by willownezz** [comment]
same here, I have been looking everywhere for this envirocore

**Comment by willownezz** [comment]
hey just saw this the mod was not approved yet that's why we can't find the core yet.
![Screenshot_99](https://user-images.githubusercontent.com/3631656/100209551-df4d9680-2ebe-11eb-91f0-ac3081f6478d.png)

**Comment by willownezz** [comment]
![Screenshot_100](https://user-images.githubusercontent.com/3631656/100210162-88948c80-2ebf-11eb-820e-1377a176383f.png)

**Comment by ValkyrieofNight** [comment]
If you install Environmental Tech through the twitch launcher it will download it's dependencies automatically. The project was approved that's why I uploaded Environmental Tech
