### ISSUE TITLE
[1.16.4] Configs are encoded in UCS-2BE BOM, which is not understood by most tools

### ISSUE THREAD

**Issue by ViRb3** [ValkyrieofNight/EnvironmentalTech#215]
I noticed that all the *.txt files, which follow your custom configuration format, are encoded in UCS-2BE BOM, instead of the standard UTF-8. This makes the files impossible to read/diff in a lot of tools such as text editors or even git, which need an explicit conversion. Could you please change them to UTF-8, just like every other config in modded Minecraft?

**Comment by ViRb3** [comment]
For the record, here is the bash command I used to convert all *.txt files to UTF-8:
```bash
find . -type f -name "*.txt" -print -exec iconv -f ucs-2be -t utf-8 -o {}.converted {} \; -exec mv {}.converted {} \; -exec sed -i 's/\xef\xbb\xbf//' {} \;
```

**Comment by ValkyrieofNight** [comment]
Fixes in latest version of ValkyrieLib
