### ISSUE TITLE
Building Void miner Tier 1 in ATM6 mod pack crashes Server

### ISSUE THREAD

**Issue by Pdiddy973** [ValkyrieofNight/EnvironmentalTech#217]
right after building Tier 1 void miner ATM6 Mining DIM, server crashed, and when Void miner was loaded /when i logged in, crashed again, how ever if it was not loaded, server would run fine.

Build tier 1 void mine in ATM6 mining DIM

[crash-2020-11-30_08.12.23-server.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5614929/crash-2020-11-30_08.12.23-server.txt)
[crash-2020-11-30_08.13.17-server.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5614930/crash-2020-11-30_08.13.17-server.txt)
[crash-2020-11-30_08.26.20-server.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5614931/crash-2020-11-30_08.26.20-server.txt)
[crash-2020-11-30_08.27.13-server.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5614932/crash-2020-11-30_08.27.13-server.txt)

**Comment by Pdiddy973** [comment]
Tried updating the mods, still getting crashes.


[crash-2020-12-07_17.28.26-server.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5655603/crash-2020-12-07_17.28.26-server.txt)

**Comment by thevortex** [comment]
this dimension is being added by the built in Minecraft feature for using json to create custom dimensions, if thats any help in debugging

**Comment by Pdiddy973** [comment]
as an update, the miner does seem to work correctly if it is in the OW, just not in the ATM^ mining dimension

**Comment by crioll** [comment]
I'm getting the same issue in the overworld, this is the crash report:
https://pastebin.com/xDYZGT47

Tier 1 miner with 2 null modifiers, 1 fe input, 1 item output

**Comment by Pdiddy973** [comment]
also getting a crash on the newest version of ET when building in a different dimension in the same mod pack
https://pastebin.com/EtV9iZ4N

**Comment by ValkyrieofNight** [comment]
Should be fixed in latest version.
