### ISSUE TITLE
Pack crashes on load

### ISSUE THREAD

**Issue by purestone9** [ValkyrieofNight/EnvironmentalTech#222]
Im running All The Mods 6 and i updated the Enviro Tech mods to their latest versions so that i can use the Laser Drill, cus its awesome and i like resources and automation
But now whenever the pack loads it crashes with the following message
The game crashed whilst rendering overlay
Error: java.lang.NoSuchMethodError: com.valkyrieofnight.vlib.core.util.tooltip.QuickTooltips.shiftForInfoTooltip()Lnet/minecraft/util/text/IFormattableTextComponent;
Exit Code: -1

**Comment by ValkyrieofNight** [comment]
What versions are you running? Seems like you forgot to update one of my mods.

**Comment by purestone9** [comment]
That was the case, but it didnt work after i updated the mod. Im going to close this one cus its already resolved about this, and from what i can tell, its now crashing becuse apothesis is having issues with Psi
