### ISSUE TITLE
Bug: Server crash assembler and refined storage crafter

### ISSUE THREAD

**Issue by Swantsy** [ValkyrieofNight/EnvironmentalTech#223]
ValkyrieLib Version: valkyrielib-1.16.4-3.0.4.1
Environmental Tech Version: envirotech-1.16.4-3.0.4.0
Description of bug: instant crash when hooking up a refined storage crafter to the assembler
Modpack Name: slightly custom ATM6
How to reproduce bug: place down a assembler and hook up a refined storage crafter.
The block itself does nothing until you hook it up to a refined storage system.

[crash-2020-12-12_16.02.27-server.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5683392/crash-2020-12-12_16.02.27-server.txt)
[crash-2020-12-12_16.03.28-server.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5683393/crash-2020-12-12_16.03.28-server.txt)
[crash-2020-12-12_16.08.58-server.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5683394/crash-2020-12-12_16.08.58-server.txt)
[crash-2020-12-12_16.09.51-server.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5683395/crash-2020-12-12_16.09.51-server.txt)

for others who might have a similar problem, we found the new mcedit!
https://www.amulet-editor.com/ we managed to delete the assembler and are currently uploading hoping it works :) please keep in mind that edited area will get the NBT data removed! so chests will emptied etc.

**Comment by ValkyrieofNight** [comment]
Have you tried updating the mod because I'm fairly certain I fixed this already.
