### ISSUE TITLE
BUG: Assembler forgets configured sides

### ISSUE THREAD

**Issue by MadPandaLord** [ValkyrieofNight/EnvironmentalTech#224]
Using Enviro tech in 1.16.4 and it seems that when i leave the server the assembler just forgets the configured sides the issue persists even when the chunks are force loaded

Minecraft version 1.16.4
ModLoader Forge
ModLoader Version 35.1.11

envirocore- 1.16.4-3.0.4.1
envirotech- 1.16.4-3.0.4.1

if you need any more info feel free to let me know

**Comment by Pdiddy973** [comment]
i also have this issue, i need to break and replace the assemblers then reconfigure the sides every time i join my local server, same versions. i am using Xnet to automate it if the effects it at all

**Comment by MadPandaLord** [comment]
Just thought i'd add some information about this bug i discovered on a server me and a friend were stood by the assembler i left the dimension and when i came back the configuration of the sides was reset even though my friend never left the chunk i can try to recreate the bug and record it if that's any help?

**Comment by ValkyrieofNight** [comment]
Fixed in latest version.
