### ISSUE TITLE
BUG: Tier 6 void miner does not get Teir 7 crystals

### ISSUE THREAD

**Issue by Pdiddy973** [ValkyrieofNight/EnvironmentalTech#226]
after running the void miner while at work this is what i got:
![image](https://user-images.githubusercontent.com/68764896/102316968-d7749580-3f44-11eb-9e6d-efc8b680965a.png)
no T7 crystals at all. 

also while building it, only completed about half and had to manually build the rest

**Comment by Pdiddy973** [comment]
using Envirocore 1.16.4-3.0.4.1
envirotech 1.16.4-3.0.4.1
valkyrelib 1.16.4-3.0.4.3

**Comment by ValkyrieofNight** [comment]
You need to put the miner in the end.

**Comment by KendirkRS** [comment]
Build the Tier 6 In the end
