### ISSUE TITLE
The auto destruction mode bug

### ISSUE THREAD

**Issue by castilio20** [ValkyrieofNight/EnvironmentalTech#229]
The auto  destruction mode doesnt give you back the matterials it just disapear and make it more hard to set to distruction mode it to easy and if you are on the void ore miner doesnt activate the auto placer and the auto placer doesnt place all the block it miss 2 or 3

**Comment by Lordmau5** [comment]
I've had this exact thing happen to me on our server just now.

We're on 3.0.5.1 but I've checked the changelog for 3.0.6.0 and it's not mentioned in there.
Is it actually fixed in that new version or is there another version that's supposed to be released soon to fix this?

**Comment by ValkyrieofNight** [comment]
This is a bug in ValkyrieLib so its mentioned in that changelog. Fixed in 3.0.6.0
