### ISSUE TITLE
[Request/Question] Energy Management

### ISSUE THREAD

**Issue by accessdenied0** [ValkyrieofNight/EnvironmentalTech#23]
Hey @ValkyrieofNight,

I love your mod to play with and one thing came up in my mind: Do you plan to add a structure to store energy? Like a multi-block Battery?

That is the only thing I would like to know,

thank you a lot,

access_denied

**Comment by ValkyrieofNight** [comment]
Yeah will be adding multi-block energy storage. Will most likely be the next multi-block structures I add.
