### ISSUE TITLE
Tier 8 Miner Crash

### ISSUE THREAD

**Issue by TheSulit** [ValkyrieofNight/EnvironmentalTech#231]
ValkyrieLib Version: 3.0.5.2
Environmental Tech Version: 3.0.5.1

Description of bug: The server crashed after building a Tier 8 miner and solar panel

(If Applicable)Modpack Name: ATM 6 - 1.3.7

How to reproduce bug:

Build Tier 8 miner and solar panel without anything else connected to them

Crash report:
https://pastebin.com/z6GbN3ka

**Comment by ValkyrieofNight** [comment]
Should be fixed in latest version
