### ISSUE TITLE
1.16 FE Output Upgrading Bug

### ISSUE THREAD

**Issue by SoulAA** [ValkyrieofNight/EnvironmentalTech#232]
ValkyrieLib Version: Valkyrielib-1.16.4-3.0.5.2

Environmental Tech Version: Envirotech-1.16.4-3.0.5.1

Description of bug: After crafting up a basic FE output, I upgraded it to Aethium tier (or any other tiers) in the Assembler. The upgrade was successful. But when I place down the Aethium tier FE output on any solar multiblock, it reverted back to the basic tier FE Output (With 1k internal buffer). Upon breaking it, it gave me an item base FE Output with white-colored name tag (same as the item showing on JEI).

Modpack Name: AllTheMods 6 Version 1.3.7, FTB Presents Direwolf20 1.16 Version 1.1.2

How to reproduce bug: Repeat the above description of bug. Reproduced consistently, even by just placing the upgraded FE block on the ground and breaking it.

**Comment by ValkyrieofNight** [comment]
Fixed in latest release
