### ISSUE TITLE
Vanilla Diamonds missing from Void miner.

### ISSUE THREAD

**Issue by newfiedog95** [ValkyrieofNight/EnvironmentalTech#235]
Resource miner program in a void miner seems to be excluding vanilla diamonds from the list of possible resources. 

MC: 1.16.4
Forge:  35.1.15
Mod: 3.0.5.1
Core: 3.0.5.2
Pack: DW20 1.2.0

**Comment by ValkyrieofNight** [comment]
Resource miner program will only mine stones, sands, dirts etc. Are you talking about the Ore Miner program? Also i've had this running on multiple test servers and am receiving diamonds just fine.
