### ISSUE TITLE
void ore miner crash 

### ISSUE THREAD

**Issue by Sunekaer** [ValkyrieofNight/EnvironmentalTech#238]
assembling a void ore miner in the void dimension corrupts the chunk and causes the game to crash and crashes the server. this happens every time the chunk is loaded 
Mod/s Affected: environmental tech + Just Another Void Dimension

https://paste.feed-the-beast.com/view/f146c672

**Comment by ValkyrieofNight** [comment]
This should be fixed in 3.0.6.0

**Comment by kriskruse** [comment]
Hate to reopen, but for the other of us. 
Are there anyway to recover the corrupted chunks or are they lost forever?
updating to the never version didn't save the chunk.
