### ISSUE TITLE
[1.11.2] Console Error java.lang.InstantiationException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserCore

### ISSUE THREAD

**Issue by ProsperCraft** [ValkyrieofNight/EnvironmentalTech#24]
https://gist.github.com/ProsperCraft/438204d98825bb0efd0f7f9e2205814f

This keeps reoccurring in console.

**Comment by ProsperCraft** [comment]
Another example - https://gist.github.com/ProsperCraft/a0c9508eb3c4d4236394dc91cda5637d

It happens when a player logs in and his base loads.

**Comment by ValkyrieofNight** [comment]
Fixed
