### ISSUE TITLE
3.0.6 Miner shift-right click not working

### ISSUE THREAD

**Issue by joklbash** [ValkyrieofNight/EnvironmentalTech#240]
3.0.5.1 was working ok. 

When I upgraded to 3.0.6, shift right click stopped building the blocks. No errors, just nothing happening as it did before. I was able to watch your video and manually build a t1 miner and it worked once finished.

**Comment by ValkyrieofNight** [comment]
Not a bug. This was removed in favor of a gui with buttons. Look inside the GUI to the left there is a button
