### ISSUE TITLE
Deconstruct voids items

### ISSUE THREAD

**Issue by Udary** [ValkyrieofNight/EnvironmentalTech#242]
DW20 pack, 
Environmental Tech 3.0.5.1
Environmental Core 3.0.5.2

When right-clicking the miner the multiblock fails to form correctly, 2 panels are missing (I believe these were modifiers). Added the other frames and modifiers manually and the laser didn't show. Added power (FE input block showed power) but miner did not show as having power. 

Right-clicked the core again, multiblock deconstructed and voided all blocks.

**Comment by ValkyrieofNight** [comment]
This is already fixed in the latest version the modpack author will need to update the mods.
