### ISSUE TITLE
BUG: Litherite Interconnect not able to be used for crafting properly

### ISSUE THREAD

**Issue by Udary** [ValkyrieofNight/EnvironmentalTech#243]
DW20 pack,
Environmental Tech 3.0.5.1
Environmental Core 3.0.5.2

Creative spawned Litherite Interconnects do not stack with Assembler created Litherite Interconnects. The ones created by the assembler do not "shift-click" into crafting grids and cannot be used in Refined Storage auto crafting. Neither item have NBT tags and look identical.

Looks like the same is happening with Redstone Imbued Obsidian Plates, but difficult to check as they are only used in the assembler. However, auto crafting does not recognise them.

**Comment by ValkyrieofNight** [comment]
Fixed in version 3.0.7.1
