### ISSUE TITLE
Missing half of Enviro tech 

### ISSUE THREAD

**Issue by Kirthbongar** [ValkyrieofNight/EnvironmentalTech#246]
Im currently using the direwolf20 modpack for Minecraft Version 1.16 and modpack version 1.2.0. When I first started playing I was missing solar arrays, lightning rods, and nano bots. I still have void ore miners and the input/ output blocks. I checked the forge page and downloaded the most up to date files and replaced the mods for enviromental tech, enviro core, and valkyrie lib with the most recent versions. This did not change anything. I also tried using the server pack for direwolf20 and that world is missing the items as well. Please let me know if i am missing a needed mod or if i need to post any sort of logs

**Comment by Kirthbongar** [comment]
I was reviewing direwolf20's videos and found that he had a mod installed called environmental energy but I cannot find that mod anywhere online.

**Comment by ValkyrieofNight** [comment]
You need the Environmental Energy mod.

https://www.curseforge.com/minecraft/mc-mods/environmental-energy/files
