### ISSUE TITLE
BUG: Litherite miner causes massive lag

### ISSUE THREAD

**Issue by WeasleyWalls** [ValkyrieofNight/EnvironmentalTech#249]
When controller was placed on the multiblock structure as shown in screenshots the controller would produce a server crippling lag putting tps at around 2, being 18-20 without it. I've check logs but no issues there.

Edit: After testing I have only been able to recreate some amount of lag when the multistructure was separated between 4 chunks where item output was in one, fe input was in a seperate one and both were not in the controller one.
![2021-01-09_13 48 46](https://user-images.githubusercontent.com/34105550/104092229-d9e7b800-5282-11eb-9216-190ad57f7498.png)
![2021-01-09_13 48 50](https://user-images.githubusercontent.com/34105550/104092230-dbb17b80-5282-11eb-9906-76d74d8918c1.png)

**Comment by ValkyrieofNight** [comment]
Have you tried using a profiler to see if it's actually that causing the tps issues? I haven't been able to reproduce this at all on my test server or in my dev environment.

**Comment by ValkyrieofNight** [comment]
No response and not been able to replicate this issue so just going to close it.
