### ISSUE TITLE
Flight in Nano Beacon still works when disabled

### ISSUE THREAD

**Issue by davqvist** [ValkyrieofNight/EnvironmentalTech#25]
A player on my modpack development server has a Nanobot Beacon with several buffs. He disabled it with a redstone signal because he wanted to save on power. Buffs like Saturation stopped but he can still fly, so the Flight Modifier still works even though the Nano Beacon is disabled and doesn't drain power.

EnvironmentalTech 0.10.5i
Minecraft 1.10.2
Forge 12.18.3.2221

**Comment by ValkyrieofNight** [comment]
Fixed
