### ISSUE TITLE
Void ore miner not working

### ISSUE THREAD

**Issue by PinguTurtl** [ValkyrieofNight/EnvironmentalTech#252]
Currently playing all the mods 6 1.3.8 version. I am trying to create the first tier void ore miner. I followed the setup step by step in accordance with the video on curse forge but for some reason, the void ore miner is not working. The only difference I see in the video and my miner is that when I put a flash memory with a program on it into the miner it doesn't show me a tick cost but it has power from my FE input.

**Comment by uecasm** [comment]
The same thing is happening in the DW20 1.16 pack (Envirocore 3.0.6.0, Envirotech 3.0.6.1).  After placing all the blocks, including the four extra blocks (it auto-placed two of the I/O blocks but didn't auto-place the 2 frames in the other slots -- ideally it should probably place none of them, since it put the I/O blocks in the "wrong" sides for where I wanted them), but then the FE bar on the controller didn't charge up (despite power being available at the FE Input), and it never showed anything except tick cost 0 after putting a programmed flash memory inside.

I tried it both in the overworld (facing up) and in the JAMD mining dimension (facing down, both close to and far away from bedrock), just in case; all behaved the same way.

**Comment by PinguTurtl** [comment]
I seem to notice when I use the auto form function, the ore miner always leaves off 2 blocks of strucutre panel to which I place. Though I don't think this makes a difference since the overall design is still the same. My void ore miner just seems to not receive any power even though my FE Input clearly has power in it. The power bar inside the Literite void miner doesn't seem to increase and it doesn't show any tickcost when a flash memory with a program is placed inside of it. Does the ore miner require a significant amount of power to work? In my case the FE Input has 1kRF in it.

**Comment by uecasm** [comment]
Double check the exact parts that you have -- as I said, I ended up with 2 laser lens holders and 1 laser core when I actually needed the other way around.  Result: it didn't place one block in a hard-to-spot location and while it *looked* like it worked it actually wasn't finished building and it didn't accept any FE power.  (The FE input block did fill up but this didn't transfer over, which sounds like exactly the same thing that's happening to you.)  The specific parts that are wrong might be different in your case, but it seems likely that you're having the same issue.

And yes, as I mentioned in the crossed out bit above, the auto-placer will only fill in the "I/O slots" with I/O blocks (FE Input and Item Output), it won't place the extra structure panels if you don't want an I/O on that side, and you have to place them manually.

Although having said that, it might not hurt to make at least two FE Input blocks -- as I discovered (and would also be nice if explained better somewhere), if you want to put a Crystal Miner chip in, this requires 1800 RF/t, which is higher than a single Litherite FE Input can accept; so you can't keep the miner powered up without at least two inputs.  I'm not sure whether it still runs very slowly in that state or if it doesn't run at all.  (I also don't recall if it was showing the laser when in that state, but I think it did.)  This is **not** your current problem though as it does display the FE value in the UI when this happens.

**Comment by danriduk** [comment]
Whats the hard to spot location ? I am currently having this issue as well, tier 1 miner is not gaining any power so i assume the multiblock is wrong when using the auto-build functionality 
- using 3 FE inputs and 1 item output in the outer ring gaps
- filled in the 2 missing structure panels that it didnt build ..
- - i have 2 laser core 1 laser lens holder, do i need a lens aswell ? but there isnt a crafting recipe for it

**Comment by danriduk** [comment]
looks like those 2 gaps that dont get filled by structure panels are for modifiers, i just filled them with 'null modifier' blocks and looks to be working now

**Comment by uecasm** [comment]
It does mention that in the tooltip. 😄  It will auto-place those if you have them on you.

**Comment by PinguTurtl** [comment]
I made sure to use 2 core and 1 laser len holder as well as another FE Input for 2k of power. Despite this, the void miner still seems to not work. Would it be possible to get into a chat together so I can show you if maybe I am just making a stupid mistake? From what I can tell, my void miner is crafted exactly how it is demonstrated in multiple videos online on youtube that shows the miner working. Could it just be the version of all the mods 6 I am on?

**Comment by uecasm** [comment]
You could take some screenshots showing all the parts in your inventory and the final build; that might possibly shed some light on it.

Also check some other common mistakes: there needs to be an uninterrupted line of sight between the bottom laser block and a bedrock block.  In particular, if you've used something that places lights around any dark areas (e.g. cave illuminator or feral flare lantern, among others), these might be blocking the line of sight (even if they're small or invisible).

**Comment by PinguTurtl** [comment]
![minecraft](https://user-images.githubusercontent.com/77362552/105072519-c256bf00-5a3a-11eb-92d7-84f70815ae73.png)
![minecraft 2](https://user-images.githubusercontent.com/77362552/105072528-c387ec00-5a3a-11eb-9f41-4cca928299ef.png)
![minecraft 3](https://user-images.githubusercontent.com/77362552/105072530-c4208280-5a3a-11eb-911e-49c0bdf9056c.png)
Here are some pictures of my setup. I tried placing the miner right side up facing the bedrock as well as up to the sky as shown in videos. Since I knew that it would work with the lasor facing the sky from the videos I left the structure as shown in the pictures.

**Comment by n4imLess** [comment]
@PinguTurtl I don't see the two modifiers in your setup/screenshots. Please double check if you have any of those in the miner. "Null modifiers" work fine. You need two, as mentioned in the tooltip of the CCU and in a comment above. And it does not seem that there is any current/up to date video about the setup online as the mod is very alpha in v3.x.

**Comment by TheRealShiu** [comment]
Hello there! I've noticed that in the envirotech-1.16.4-3.0.6.1.jar\data\envirotech\envirotech\void_miner_program\ore.json file the '"tick_energy": 1000' is written as '"energy_tick": 1000' . After changing this minor error the mod and the first stage of the miner works again.
