### ISSUE TITLE
Upgrading modifiers not showing working.

### ISSUE THREAD

**Issue by Deztras** [ValkyrieofNight/EnvironmentalTech#253]
When I attempt to upgrade a modifier say for example and Amplification modifier to the tier3 version it remains the same.  I was able to get a couple to upgrade properly however since the latest update I can not get any to upgrade.

**Comment by Lurae** [comment]
I too ran in to this issue, if you place the modifier and then break it and try again, it works. simple but annoying work around, just place and break every modifier before trying to upgrade :)

**Comment by ValkyrieofNight** [comment]
This is fixed and coming next update

**Comment by ValkyrieofNight** [comment]
Fixed in latest release.
