### ISSUE TITLE
[1.16.4] Mica does not appear to be generating

### ISSUE THREAD

**Issue by Zarkov2** [ValkyrieofNight/EnvironmentalTech#254]
ValkyrieLib Version: 3.0.6.1
Environmental Core Version: 3.0.6.0
Environmental Tech Version: 3.0.6.1
(DW20 pack version 1.3.1 for 1.16.4)

I have been unable to get any Mica to generate, tested with both Resource or Ore void miners.

3x Tier 3 void miners, all with 8 frequency upgrades and running for 45+ minutes (each, as both Ore and Resource miners). No Mica have so far been generated. All miners have been running in a Flower Forest biome (if that could make a difference).

edit: The Environmental Tech is version 3.0.6.0 according to the in-game mod list, 3.0.6.1 was in the file name.

**Comment by AwesomeSeal** [comment]
I'm running the same pack and version, here is how much I have mined using the resource miner:
https://imgur.com/a/gJdmD4o
Mica does not appear to be on the table, or it is incredibly rare.

**Comment by ValkyrieofNight** [comment]
Put your miner in the nether or the end.

**Comment by Zarkov2** [comment]
Thanks @ValkyrieofNight, placed one in the nether and got Mica.
