### ISSUE TITLE
MC[1.16.4] ET[3.0.6.1] Refined Storage[1.19.11] Impossible to automate any crafting in ET.

### ISSUE THREAD

**Issue by LTenshi** [ValkyrieofNight/EnvironmentalTech#257]
Good day

I am 100% aware that this may be a refined storage problem, but it seems that currently, only this mod is having such an issue.

I've been trying to get things automated with Refined Storage crafting mechanics and ran into a problem where multiple items are not detected as crafted. For instance, if I request a Redstone Imbued Obsidian Plate via the system the item will be crafted (It's a major pain to automate the new assembler without using Xnet btw) and it will appear as a separate entry in the system. Refined storage will not detect that it has indeed crafted the component and the crafting operation will hang forever.

Doubly confusing if I try and request something that utilizes that Redstone Imbued Obsidian Plate, it will try and craft the plate again instead of using the existing plates inside of the system, ergo making a vast majority of ET recipes as uncraftable using Refined Storage.

If anything needs explaining, feel free to leave a comment.

**Comment by walia6** [comment]
Having the same issues with AE2

**Comment by walia6** [comment]
Appears this is a clone of #230

**Comment by LTenshi** [comment]
So it is.
