### ISSUE TITLE
Solar T6 only generating 1kFE

### ISSUE THREAD

**Issue by Phate339** [ValkyrieofNight/EnvironmentalTech#259]
Playing with the ATM6 modpack and after it updated the solar to 1.4.0 (enviroTech 3.0.6.0) the generation  o solar power is non-existent.

Is it just me??? i tried rebuilding the structure but the result is the same.

**Comment by ValkyrieofNight** [comment]
You need to upgrade your FE Outputs they have a limit on how much they can transfer
