### ISSUE TITLE
Crash when looking up Mica using JEI

### ISSUE THREAD

**Issue by MakeLord95** [ValkyrieofNight/EnvironmentalTech#26]
When you look up where to get Mica, you get this (http://pastebin.com/QCpjxmTm) crash.

Versions:
Minecraft: 1.10.2
Forge: 12.18.3.2221
JEI: 1.10.2-3.14.7.415
Environmental Tech: 1.10.2-0.10.6a (Rolling ET to 0.10.5i works fine)
ValkyrieLib: 1.10.2-0.10.6

**Comment by AntiDruid** [comment]
It happened when I hovered my mouse on the middle item in the void miner recipes. But can confirm this is an issue.

My log: http://pastebin.com/YgDssgNP

Minecraft 1.10.2
Forge: 12.8.3.2239
JEI: 1.10.2-3.14.7.415
Environmental Tech: 1.10.2-0.10.6a
ETLunar: 1.10.2-0.10.6a
ValkyrieLib: 1.10.2-0.10.6

**Comment by ValkyrieofNight** [comment]
Ugh JEI Needs to stop changing its api every 5 updates

**Comment by ValkyrieofNight** [comment]
Fixed in next version!
