### ISSUE TITLE
BUG: Void Ore Miner can break bedrock with auto utilities

### ISSUE THREAD

**Issue by JAMEZJB** [ValkyrieofNight/EnvironmentalTech#263]
**ValkyrieLib** Version: 3.0.6.1
**Environmental Tech Version:** 3.0.6.0
**Description of bug:** Using the auto-destruct with the void ore miner can cause bedrock to break. I don't know if this is intentional as am new to the mod, however, I saw no documentation showing that this should be the case. Please correct me if I'm wrong.
**(If Applicable)Modpack Name:** FTB Presents Direwolf20 1.16 (1.6.4)
**How to reproduce bug:** Place void ore miner on top of bedrock layer in the overworld. Have not tested other dimensions, I don't think it would make a difference.

![enviromental tech bug report 10mb](https://user-images.githubusercontent.com/38116836/106002742-62e75780-60a9-11eb-87e8-c6d17ca90137.gif)

**Comment by ValkyrieofNight** [comment]
Thank you that is not intended I will fix.

**Comment by Slaymeister** [comment]
Link back  https://github.com/AllTheMods/ATM-6/issues/991

**Comment by ValkyrieofNight** [comment]
Fixed in version 3.0.7.1
