### ISSUE TITLE
Resource Miner not generating Mica

### ISSUE THREAD

**Issue by dlmcduff** [ValkyrieofNight/EnvironmentalTech#267]
Hi,
I've been running the Pladium void miner with resource miner memory card in the overworld, nether and end for more than 4 hours in each location, in some cases (e.g. Nether) running for overnight for 8 hours. I have gotten plenty of alabaster colors (and other resources) but no mica. I'm playing ATM6 1.5.0.zip in a single-player world. 

Mods: 
Environmental Materials
ValkyrieofNight
enviromats-1.16.4-2.0.6.0.jar

Environmental Tech
ValkyrieofNight
envirotech-1.16.4-3.0.6.1.jar

Environmental Core
ValkyrieofNight
envirocore-1.16.4-3.0.6.0.jar

Environmental Energy
ValkyrieofNight
enviroenergy-1.16.4-3.0.6.0.jar

**Comment by LordSkaldor** [comment]
im also having the same issue. i left it running overnight in the nether, and overworld.
I switched to the end a few moments ago to test, but im expecting a similar result.

**Comment by ValkyrieofNight** [comment]
I will look into it.

**Comment by dlmcduff** [comment]
Thanks!

**Comment by ValkyrieofNight** [comment]
Works fine. Maybe update?

**Comment by dlmcduff** [comment]
@ValkyrieofNight im currently on ATM 6 1.5.1 release and the latest Environmental mods. I can't update anymore. :) Also, in addition to getting every resource (alabaster, pumice, crying obsidian, etc.) EXCEPT Mica. Also, the ?beacon light? is not appearing after my upgrade to 1.5.1. If it helps, my mine is pointed at the ceiling bedrock in the Nether. Here are my Environmental mod versions. 

Environmental Core
ValkyrieofNight
envirocore-1.16.5-3.0.7.0.jar
Environmental Energy
ValkyrieofNight
enviroenergy-1.16.5-3.0.7.0.jar
Environmental Materials
ValkyrieofNight
enviromats-1.16.5-2.0.7.0.jar
Environmental Tech
ValkyrieofNight
envirotech-1.16.5-3.0.7.0.jar

Thanks.

**Comment by dlmcduff** [comment]
Images of my resource miner in the Nether and the collected resources after 1.5 hours. 

[https://imgur.com/DTY9bUC](url)
[https://imgur.com/TspX20G](url)

**Comment by ValkyrieofNight** [comment]
I've tested the resource miner in both the end and the nether and successfully gotten mica within a few minutes of mining on these versions.

**Comment by dlmcduff** [comment]
Okay. I’ll do some testing in a new world. Thanks for looking into it.
