### ISSUE TITLE
[1.16.5] Can't craft Litherite Interconnect on a dedicated server

### ISSUE THREAD

**Issue by XFactHD** [ValkyrieofNight/EnvironmentalTech#270]
When I put Redstone Imbued Obsidian Plates into the Assembler together with Litherite Crystals the client and server console are spammed with debug output as can be seen from the excerpts from the logs and the crafting process is not started.
If I then click on any one of the items in the Assembler slots, all the items are instantly transferred back to my inventory.
Leaving the Assembler's GUI appears to leave the items in the Asembler but reentering the Assembler GUI makes them instantly reappear in my inventory.
The order of insertion and wether none, one or both of the stacks are inserted by shift click doesn't matter.

The same recipe works perfectly fine in a singleplayer world, albeit with the same log spam (and some more related to side configs).

**Versions:**
Forge: 1.16.5-36.0.10
Environmental Core: 1.16.5-3.0.7.0
Environmental Tech: 1.16.5-3.0.7.0
ValkyrieLib: 1.16.5-3.0.7.0

**Logs:**
Client: https://gist.github.com/XFactHD/9f1ed9df1f542b55aa7db7928c55c3cf
Server: https://gist.github.com/XFactHD/5815e0294f817ae11f6abbeba4cf979a

**Comment by Cavecanem** [comment]
I'm experiencing this in a single player world as well. I noticed it when trying to automate with Xnet. What happens is when it is finished crafting, any items you put in afterwards will be transferred back to the inventory. If you put in a stack at once it will still craft a stack, but after that you can't use it anymore.
A workaround is to break the Assembler and place it down again. Then it works for another set of crafts. It quickly gets tedious though, and you can't really automate it.

**Comment by ValkyrieofNight** [comment]
I will look into it tonight

**Comment by XFactHD** [comment]
Just tried the workaround, can confirm that it works after breaking and replacing it.

**Comment by ValkyrieofNight** [comment]
Fixed in version 3.0.7.1
