### ISSUE TITLE
[1.16.4] Curse doesn't provide the file for 3.0.7.0 

### ISSUE THREAD

**Issue by martymarty004** [ValkyrieofNight/EnvironmentalTech#271]
The new version (3.0.7.0) was not made available for 1.16.4

**Comment by ValkyrieofNight** [comment]
This is a bug with curseforge, the file is on there.

**Comment by ValkyrieofNight** [comment]
https://www.curseforge.com/minecraft/mc-mods/environmental-core/files

https://www.curseforge.com/minecraft/mc-mods/environmental-energy/files

https://www.curseforge.com/minecraft/mc-mods/environmental-tech/files

**Comment by martymarty004** [comment]
So I just download the latest 1.16.5 version and it will work fine?

**Comment by ValkyrieofNight** [comment]
I only made it available for 1.16.5 because that's all I have tested it for. At this point you should probably move your pack over to 1.16.5 since pretty much all mods are compatible.

**Comment by martymarty004** [comment]
I'm waiting for a more stable version for Forge, I think I will stay on this release for a while, thanks.
