### ISSUE TITLE
Missing Texture for the interdimensional modifier

### ISSUE THREAD

**Issue by martymarty004** [ValkyrieofNight/EnvironmentalTech#272]
The texture for the interdimensional modifier is missing, there is also an error in the logs:

`Using missing texture, unable to load envirocore:textures/block/modifier/_interdimensional_under.png : java.io.FileNotFoundException: envirocore:textures/block/modifier/_interdimensional_under.png`

`Using missing texture, unable to load envirocore:textures/block/modifier/_interdimensional2.png : java.io.FileNotFoundException: envirocore:textures/block/modifier/_interdimensional2.png`

I think this is caused by the texture files starting with a capital letter in the jar file
![image](https://user-images.githubusercontent.com/61474670/106794279-e4feef80-6658-11eb-977c-45828b26851e.png)

**Comment by ValkyrieofNight** [comment]
I haven to finished the modifier yet but I will fix that when I work on it.

**Comment by ValkyrieofNight** [comment]
Fixed in version 3.0.7.1
