### ISSUE TITLE
Forced Server Stop Caused by Assembler

### ISSUE THREAD

**Issue by KeonaBT** [ValkyrieofNight/EnvironmentalTech#273]
Version: 1.16.5-3.0.7.0

This mainly regards the spam caused by being unable to craft in the assembler.  I saw that bug reported and have been using the work around by picking up and replacing.

However, if after I place the resources in and start crafting then exit the UI and reopen it, it will spam the console with warnings and the server will shut down with no crash report.  Recreated the scenario after server restarted and a second crash occurred with no crash report.  (My server doesn't recognize it as a crash and doesn't automatically restart, I have to manually start the server.)

Current work around is to pickup, replace, setup your crafting to autopull out and then wait for it to be done.  Then repeat the process.

**Comment by KeonaBT** [comment]
Update: Found it doesn't crash the server, the spam literally forces the server to stop.
![image](https://user-images.githubusercontent.com/78609493/107060180-47acd400-679c-11eb-860a-bb2db46a025d.png)

**Comment by ValkyrieofNight** [comment]
Update I fixed this and put an update out a couple days ago
