### ISSUE TITLE
Assembler only completes 1 craft then has to be broken / placed to continue

### ISSUE THREAD

**Issue by jeffphil** [ValkyrieofNight/EnvironmentalTech#276]
Mod version: 1.16.5-3.0.7.0
Forge version: 1.16.5-forge-36.0.14
Other info: modpack "FTB Presents Direwolf20 1.16"

When I craft an item in the assembler it will work the first time but placing the items in the assembler the second time does not get a result. The first craft can be a single item or multiple items but after that to continue the Assembler has to be broken then replaced.

**Comment by ValkyrieofNight** [comment]
This is fixed, update the mod.
