### ISSUE TITLE
[Config] Adjusting Nano Bot Beacon power usage

### ISSUE THREAD

**Issue by Lukas45** [ValkyrieofNight/EnvironmentalTech#30]
Currently there's no configs at all for the Nano Bot Beacon, but there need to be at very least a config for its power consumption.
Gaining permanent, with unlimited range,
- Strength II
- Resistance II
- Haste II
- Fire Resistance II
- Regeneration
- Water Breathing
- Saturation
- Flight

on a Tier 3 Beacon for 1800rf/t, is kinda ridiculous.
For us (the server), it needs to be at least 20k rf/t for that bunch, to maybe seem somewhat acceptable

**Comment by ValkyrieofNight** [comment]
ET 2 will contain ability to change power requirements for individual modifiers.

**Comment by Lukas45** [comment]
Is this implemented yet in ET2? Or is that for a future update, or does it work with the current config file with some extra added?
We're gonna add this soon to our modpack, and currently the only related configs are:
```
    multiblocks {

        components {

            modifiers {
            }

            structure_frames {
            }

            structure_panels {
            }

        }
```
and
```
nanobot_beacon {
            # Is Module Enabled? [default: true]
            B:enabled=true

            personal {
                # Is Module Enabled? [default: true]
                B:enabled=true
            }

            ranged {
                # Is Module Enabled? [default: true]
                B:enabled=true
            }

        }
```

**Comment by ValkyrieofNight** [comment]
Currently there are no modifiers in ET 2 but will be coming soon. The modifiers will have editable power requirements.

The Nanobot Beacon is not implemented yet but will be in a future update.
