### ISSUE TITLE
[Beacon modifyers] Recipes accepts any enchanted book

### ISSUE THREAD

**Issue by Discomanco** [ValkyrieofNight/EnvironmentalTech#31]
When crafting the Resistance and Haste modifiers, the enchanted books can be any enchanted book, and doesn't have to be specifically Protection IV or Efficiency V.
http://imgur.com/a/Nk9Le

Environmentaltech-1.10.2-0.10.6b
(not tested with the mod standalone)

**Comment by ValkyrieofNight** [comment]
No longer updating the 1.12.2 version
