### ISSUE TITLE
ore/resource miner not showing ore/resources in jei correctly shows blank for items (1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [ValkyrieofNight/EnvironmentalTech#32]
forge: 1.11.2-2255
environmental: environmentaltech-1.11.2-0.11.0d
jei: jei_1.11.2-4.2.8.244
jer: JustEnoughResources-1.11.2-0.6.3.4

shown below:

![2017-03-13_10 07 39](https://cloud.githubusercontent.com/assets/14084377/23836982/fc896266-07d4-11e7-922a-f2e5e6a664fa.png)

![2017-03-13_10 08 00](https://cloud.githubusercontent.com/assets/14084377/23836984/053dacd2-07d5-11e7-9a4b-dd6d4ddc8259.png)

**Comment by EmosewaGamer** [comment]
yup

**Comment by ValkyrieofNight** [comment]
Sorry 1.11.2 is no longer supported due to MC 1.12 and ET 2. ET 2 may be back-ported at some point however.
