### ISSUE TITLE
Clear glass missing texture

### ISSUE THREAD

**Issue by Endmateria** [ValkyrieofNight/EnvironmentalTech#33]
Clear glass texture is missing.  
Forge 1.11.2 - 13.20.0.2260
Environmentaltech 1.11.2-0.11.0d

![2017-03-25_04 10 17](https://cloud.githubusercontent.com/assets/25782793/24325610/9e179a2a-1172-11e7-8207-9d784a87c9da.png)

**Comment by LucyMarieKiwi** [comment]
I'm having the same issue.
Forge - 1.11.2 - 13.20.0.2304
Environmental tech - 1.11.2 -  0.11.0d

**Comment by ValkyrieofNight** [comment]
Sorry 1.11.2 is no longer supported due to MC 1.12 and ET 2. ET 2 may be back-ported at some point however.
