### ISSUE TITLE
Player proximity - Solar panels and void ore miner

### ISSUE THREAD

**Issue by Tuffnoodle** [ValkyrieofNight/EnvironmentalTech#34]
Hello! This issue is in regards to a situation we've run into our FTB Beyond server:[ forum post](https://mineyourmind.net/forum/threads/ftb-beyond-problem-with-environmental-tech-mod.24767/)

It seems there's some sort of proximity issue where the player has to be within a certain range for the machines to function, regardless of being in the same chunk. We were wondering if this was an intended feature or a bug!

Edit: Both machines work when the chunk is loaded, regardless of player proximity in Single Player; this is an issue with the how the mod interacts in the FTB Beyond pack.

**Comment by ValkyrieofNight** [comment]
FTB Beyond seems to have chunk loading issues. I am running it on my server also and chunk loading has been weird. Most likely a modpack bug.
