### ISSUE TITLE
Night vision modifier not working 

### ISSUE THREAD

**Issue by djpanda** [ValkyrieofNight/EnvironmentalTech#36]
We are using the "New Frontier" Pack from Curse ive build an T4 Nano Bot Beacon With 2x Regeneration, 2x Saturation, 1x Resistance, 1x Water Breathing, 2x Haste,1x Night Vision, 1x Strength and 6x Modifier Core but the Night Vision Effekt didnt get activated.

 Version 1.11.2-0.11.0a

**Comment by zashra00** [comment]
Does the pack have draconic evolution?

**Comment by djpanda** [comment]
no draconic evolution
That are the included mods ->
https://minecraft.curseforge.com/projects/the-new-frontier/relations/dependencies

**Comment by zashra00** [comment]
Are you wearing anything that gives night vision?

**Comment by djpanda** [comment]
No not realy the pack does have the posibility to craft a nightvision helm but now i dont wear it  Others i didnt had seen that i dont get a nightvision effect from the Nano Beacon

**Comment by zashra00** [comment]
That's odd I'm in beyond and the only time I don't get it is when I have something else that gives night vision

**Comment by zashra00** [comment]
I'll dl the pack and see what's up

**Comment by ValkyrieofNight** [comment]
Sorry 1.11.2 is no longer supported due to MC 1.12 and ET 2. ET 2 may be back-ported at some point however.
