### ISSUE TITLE
Drawing Power from Solar Panel? 1.10.2-0.10.6a (1.10.2-0.10.6a)

### ISSUE THREAD

**Issue by zjgruber** [ValkyrieofNight/EnvironmentalTech#37]
It seems many mods don't connect to a Solar Panel Controller (to draw power), aside from EnderIO.

Tested with Tier 4 Controller (None Work):
-Mekanism Universal Cable AND Energy Cube (9.2.1)
-Draconic Evolution Energy Pylon AND I/O Crystals (2.0.8.177)
-Actually Additions Phantom Energyface (1.10.2-r98)
-Slugs EU and RF Converters (1.1 (1.0A))

This makes it very problematic if I want to use ET and not EnderIO, or use ET an an expert/hard modpack that makes EnderIO later in progression than ET.

**Comment by ValkyrieofNight** [comment]
ET uses 100% Forge RF so if there is incompatibility its due to those mods not implementing Forge RF properly.
