### ISSUE TITLE
config options

### ISSUE THREAD

**Issue by cmspeedau** [ValkyrieofNight/EnvironmentalTech#41]
an ability in minecraft 1.10.2.. aka turn off tier 1 of the solar panel controller and same for the resource miner.. that only tier 2 and up are only craftable..

**Comment by ValkyrieofNight** [comment]
Unfortunately now that ET 2 is out I no longer have time to update the 1.10.2 version of the mod. A ET 2 back-port may be made at some point but for now not more features will be added to the original ET.
