### ISSUE TITLE
java null pointer exception while loading Minecraft

### ISSUE THREAD

**Issue by Hypsellis** [ValkyrieofNight/EnvironmentalTech#43]
I get this crash when loading Minecraft. I use Environmental Tech 0.11.0d, Minecraft 1.11.2 and Forge 13.20.0.2309 https://pastebin.com/3wUf507p

**Comment by ValkyrieofNight** [comment]
Sorry 1.11.2 is no longer supported due to MC 1.12 and ET 2. ET 2 may be back-ported at some point however.
