### ISSUE TITLE
Game Crashes when looking at specific blocks

### ISSUE THREAD

**Issue by mountain01** [ValkyrieofNight/EnvironmentalTech#44]
While playing on a server with this mod I tried using the assembler to construct the tier one solar panel, the server crashed. I don't have the logs for that crash but now when ever I look at the structure block (I'm using tier 1 basalt structure blocks) the game crashes with this error report. Other blocks in the mod can be looked at and broken but not these two that ended up getting placed.

https://pastebin.com/KjNTdYgP

**Comment by ValkyrieofNight** [comment]
Sorry 1.11.2 is no longer supported due to MC 1.12 and ET 2.
