### ISSUE TITLE
Doesn't work on 1.12

### ISSUE THREAD

**Issue by Seegras** [ValkyrieofNight/EnvironmentalTech#45]

**Comment by Bass2style** [comment]
this is a 1.10.2 mod, this is normal that it doesn't work...

**Comment by Jacky1356400** [comment]
https://minecraft.curseforge.com/projects/environmental-tech/files/2459030

**Comment by Morpheus1101** [comment]
I've made the Tier1 for 1.12 and it works fine

**Comment by Ricket** [comment]
It was Seegras' way of pointing out that the mod had not been updated to 1.12 yet. This issue should just be closed now that 1.12 is out.
