### ISSUE TITLE
Valkyrielib uses old RF API

### ISSUE THREAD

**Issue by Boqzo1** [ValkyrieofNight/EnvironmentalTech#48]
Game crashes on load due to it using the old RF API

**Comment by ValkyrieofNight** [comment]
Whats funny about that is that I completely got rid of the old RF API a long time ago.

**Comment by ValkyrieofNight** [comment]
Ugh found the reason and will have a fix out soon.

**Comment by ValkyrieofNight** [comment]
Released a fix
