### ISSUE TITLE
[1.12] Getting all other crystals bar Litherite

### ISSUE THREAD

**Issue by Morpheus1101** [ValkyrieofNight/EnvironmentalTech#49]
Are all other crystals implemented as yet and if so, how are they obtained?

**Comment by ValkyrieofNight** [comment]
The void miners obtain the crystals. Each tier void ore miner obtains the next tier crystal. You'll need to progress through each tier void ore miner.

**Comment by Paul17041993** [comment]
@ValkyrieofNight their corresponding filter colour will work to boost the chance correct?

**Comment by Morpheus1101** [comment]
Last i checked the colored lenses were not functional yet, unless there has been an update recently

**Comment by ValkyrieofNight** [comment]
The colored lenses work in the latest update however the crystals will not use regular colored lenses to increase mine rate. They will be getting their own lens/lenses to increase rate.

**Comment by Paul17041993** [comment]
some hours in and I haven't seen any tier 2 crystals yet on a tier 1 miner, it has one tier 1 crystal though, seems like the upper tier chance is a little low for the early tiers?

**Comment by Morpheus1101** [comment]
I agree, thats why i built multiple void miners

**Comment by ValkyrieofNight** [comment]
I have doubled the spawn rate in latest version but for me to balance further I will need to play test the mod myself. Balances will come :D
