### ISSUE TITLE
Feature request: Making the solar panels less spiky

### ISSUE THREAD

**Issue by FnordMan** [ValkyrieofNight/EnvironmentalTech#5]
Any chance you could make the solar panels output a steady stream of power instead of large spikes? Using EnderIO Conduits/Dimensional transceivers here. (as Mekanism cables have small issues with some other mods, bug on Mek's end, not yours)

One of those quality of life sort of improvements.

**Comment by ValkyrieofNight** [comment]
Yeah can do.

**Comment by ValkyrieofNight** [comment]
Added in latest update. 0.10.5g

**Comment by FnordMan** [comment]
Works great, thanks for making the change. Now the induction matrix knows what to make of things.
