### ISSUE TITLE
[1.12] Void Ore Miner dosent complete

### ISSUE THREAD

**Issue by Morpheus1101** [ValkyrieofNight/EnvironmentalTech#50]
I had multiple stacks of all blocks an although the structure looks complete, the usual message saying structure complete and the beam of light shooting down to bedrock dosent occur.  Being this is in Alpha, i am unsure of if this part of the mod is still a WIP

![2017-08-03_17 42 45](https://user-images.githubusercontent.com/10524952/28911333-48c7d112-7873-11e7-9afe-56925f0c0ada.png)
![2017-08-03_17 42 58](https://user-images.githubusercontent.com/10524952/28911335-4becb196-7873-11e7-9b02-c7cac80d049b.png)

**Comment by ValkyrieofNight** [comment]
The multiblock complete message should still work. Rendering has not been added to void miners yet and will be out in next update.
