### ISSUE TITLE
Coloured lenses not forming Tier 1 Void Ore Miner when used in place of a clear lens [1.12]

### ISSUE THREAD

**Issue by Cakefire1121** [ValkyrieofNight/EnvironmentalTech#51]
After various attempts ranging from simply replacing the clear lens of a completed structure to rebuilding the structure with only a coloured lens in inventory (which built the structure itself, but did not complete the multiblock, until the coloured lens was replaced with a clear lens, where it successfully formed), I have come to the conclusion that coloured lenses simply do not work. 

Additionally, according to the assembler, the multiblock needs "Clear Laser Lens or any Colored variant", so if the coloured lenses are not supposed to work with the Tier 1, then the text should be amended to make that clearer.

Pack: Unstable 1.12

Thank you.

**Comment by ValkyrieofNight** [comment]
Colored lenses are bugged at the moment and dont work. They will be fixed next release.
