### ISSUE TITLE
[1.12] Tier 5 & 6 Void Ore Miner not giving crystals past Erodium

### ISSUE THREAD

**Issue by otub** [ValkyrieofNight/EnvironmentalTech#52]
EnvTech Version: 2.0.0b
Forge Version:  2443

I've waited a long time(as you can see) and it has given me no crystals past Erodium 
![javaw_2017-08-11_12-56-31](https://user-images.githubusercontent.com/30933945/29223737-a2e99fae-7e95-11e7-8a92-0ec23fda286a.png)

**Comment by ValkyrieofNight** [comment]
Thanks will take a look tonight.

**Comment by ValkyrieofNight** [comment]
Fixed in next 2.0.0d release.
