### ISSUE TITLE
[1.11.2] Support for Thermal Dynamics Oil Sand/Shale "Ores"

### ISSUE THREAD

**Issue by spaz926** [ValkyrieofNight/EnvironmentalTech#53]
I've had my Ore/Resource Miners running, but have yet to see Oil Sand/Shale show up. Both blocks are included in the OreDictionary prefix 'ore'.

Do the miners not support these ores?

**Comment by ValkyrieofNight** [comment]
The miners have loot tables. You can add them to the loot tables if you desire. May add them to the defaults in next update.

**Comment by spaz926** [comment]
Thanks for the reply. I've been digging around in your jar file to try and find the loot tables, but have yet to find it. If you could point me in the right direction that'd be much appreciated.

I also took a look at the Thermal Foundation source to ensure they contain the `ore` prefix in the OreDictionary.

**Comment by ValkyrieofNight** [comment]
The loot tables get generated and put in the configs folder. They are simple Json files. Look at the other items to see how to add them.

**Comment by spaz926** [comment]
Oh. Okay. I found the config files. Thanks.

I was looking in the unpacked jar of the mod for wherever these config files get generated and was having no luck finding it.
