### ISSUE TITLE
[1.12] Crash on startup

### ISSUE THREAD

**Issue by NillerMedDild** [ValkyrieofNight/EnvironmentalTech#54]
Minecraft 1.12
Forge 1.12-14.21.1.2443
Environmental Tech 1.12-2.0.1a
ValkyrieLib 1.12-2.0.1a

Hey!
I get a [crash](https://pastebin.com/rN1Rs0m4) on startup, with the newest versions.
I edited some ore weights in the config for the Void Miner, and changed the energy production of solars, in case that makes a difference.
On a side note, the new iteration of the mod looks really cool, I look forward to playing with the new additions!

**Comment by ValkyrieofNight** [comment]
Thanks. It looks like you may have an invalid json there. I need to add in error checking so it doesn't crash when invalid. I'll probably add that in tonight after work.

**Comment by ValkyrieofNight** [comment]
Will get a fix out after work. Ran out of time last night to add in handling for invalid entries.

**Comment by NillerMedDild** [comment]
I deleted the configs, and all is well, thanks :)

**Comment by NillerMedDild** [comment]
I see amount is no longer supported in the json for Void Miners, I bet that invalidaded my jsons, right?

**Comment by ValkyrieofNight** [comment]
It could have yeah

**Comment by NillerMedDild** [comment]
I found the cause of the crash. I set a weight to 0 - I thought it would've just turned the given block off.

**Comment by ValkyrieofNight** [comment]
Yeah makes sense. To remove a block just remove the whole entry.

**Comment by NillerMedDild** [comment]
Scrath that, I was able to set the weight of Yellorite to 0, weird.
Anyway, I'll leave you to it, thanks again :)
