### ISSUE TITLE
[1.12][2.0.1a] Digital Guide not spawning

### ISSUE THREAD

**Issue by savosdarkran** [ValkyrieofNight/EnvironmentalTech#55]
Hey,

When I start a new world in 1.12 with 2.0.1a I do not spawn in with a digital guide.  Is this by design?  I don't even see it in the creative menu and I went through the config a few times to see if there was an option I was missing ( maybe still am ).

Let me know.

Cheers.

**Comment by ValkyrieofNight** [comment]
The guide currently doesn't exist in the 1.12 version. This feature will be added in a future update.

**Comment by savosdarkran** [comment]
Seems good.  I was just making sure I didn't derp :)

**Comment by Firestar311** [comment]
Any idea when you will be able to get it added? I would love to use this mod in my modpack, but there is no way to know what resources and how many are needed.

**Comment by ValkyrieofNight** [comment]
If you smack a controller with the assembler it will telyou all the required blocks. No ETA on the guide yet.

**Comment by Timeslice42** [comment]
Is this the assembler?

https://i.imgur.com/8OJaNjW.png

**Comment by Seegras** [comment]
Yes, it tells me however I need "structure block" but I only have "structure frame".

**Comment by ValkyrieofNight** [comment]
The guide is now part of ValkyrieLib and will eventually contain guides for all my mods. It is avaliable in game and more information will come with updates.
