### ISSUE TITLE
[1.12] Void Botanic Miner

### ISSUE THREAD

**Issue by NillerMedDild** [ValkyrieofNight/EnvironmentalTech#56]
Hey :)

Minecraft 1.12
Forge 1.12-14.21.1.2443
EnvironmentalTech 1.12-2.0.1a
Modpack: Enigmatica 2, version 1.04a

Turning off the Void Botanic Miner in the config, removes about 50% of all recipes from the mod - All Solar Arrays, all Solar Panels, Litherite, and a lot more.

[Forced crash](https://gist.github.com/NillerMedDild/c95b7b05c0fff778bee6e809fd01ec99)

Please let me know if there's anything else you'd like to know.

**Comment by ValkyrieofNight** [comment]
Yeah its on my to-do list. Hopefully a fix will be out within the next few updates.

**Comment by NillerMedDild** [comment]
Sounds good, thank you.

**Comment by ValkyrieofNight** [comment]
Fix coming next build

**Comment by NillerMedDild** [comment]
I appreciate it :)
