### ISSUE TITLE
Version 2.0.2a has no 1.12 support

### ISSUE THREAD

**Issue by Ash70** [ValkyrieofNight/EnvironmentalTech#57]
Not sure if this is intended or an oversight? But latest version 2.0.2a only has 1.12.1 tag on curseforge.

**Comment by ValkyrieofNight** [comment]
It doesn't support 1.12 but I will be putting out a version tomorrow with 1.12 support. 2.0.2cwill be the version.

**Comment by ValkyrieofNight** [comment]
Version out for 1.12
