### ISSUE TITLE
[1.12.1] Wrong JEI Tooltips

### ISSUE THREAD

**Issue by EmosewaGamer** [ValkyrieofNight/EnvironmentalTech#58]
On the latest version of the mod, the tooltips on the JEI tabs for the Void Resource Miners say "Void Ore Miner". 
![image](https://user-images.githubusercontent.com/25333164/29624874-81fa2d1a-882a-11e7-8199-e730e8914aa0.png)

**Comment by ValkyrieofNight** [comment]
Fix coming in 2.0.2c
