### ISSUE TITLE
Request: fix your ores to have required tool / mining level

### ISSUE THREAD

**Issue by Kaisoul** [ValkyrieofNight/EnvironmentalTech#6]
I have an issue with your ores now to explain the issue in detail my pick axe is a tinkers construct pickaxe made with  paper head,paper binding/knightslime handle with 5 reinforced plates added & a obsidian sharpening kit added to the tool.

So the tool will mine Cobalt level ores and will mine ores faster if the tool is a higher minging level then the ore in question.

Your ores are not either requiring a pickaxe to mine or they don't have a min mining level set so mining each one of your ores is like mining obsidian...

was wondering if this can be corrected in a future update?

**Comment by ValkyrieofNight** [comment]
Fixed in latest update. 0.10.5g

**Comment by Kaisoul** [comment]
thank you for the speedy update.
