### ISSUE TITLE
[1.12.1] Solar Array Efficiency config

### ISSUE THREAD

**Issue by NillerMedDild** [ValkyrieofNight/EnvironmentalTech#61]
Hey!

Is the solar array efficiency supposed to increase the max amount of RF generated by a Solar Array? I'm not seeing any difference in energy generation from 100% to 1000% for Tier 1 Solar Arrays, nor any other percentage.

Minecraft 1.12.1
Forge 1.12.1-14.22.0.2462
environmentaltech-1.12.1-2.0.2d

**Comment by ValkyrieofNight** [comment]
Check the higher tier panels. Each array has a max efficiency that it can operate at. Configs for those max efficiencies will come in a future update. Let me know if you still don't get results.

**Comment by NillerMedDild** [comment]
The default config setting, and the default * 10 gives the exact same energy generation.

Config:
![billede](https://user-images.githubusercontent.com/21295394/29749057-1c803f72-8b24-11e7-94a8-4930b6300cc3.png)

**Comment by NillerMedDild** [comment]
The energy generation when the configs are default, and default *10 are the exact same.
Config:
![billede](https://user-images.githubusercontent.com/21295394/29749082-b173e84a-8b24-11e7-8f01-2abfa97d4265.png)

**Comment by NillerMedDild** [comment]
The max efficiency config doesn't do anything atm.

**Default**:
Tier 1 549
Tier 2 3050
Tier 3 12005
Tier 4 39771
Tier 5 118943
Tier 6 332254

**Low**:
Tier 1 270
Tier 2 750
Tier 3 4508
Tier 4 12393
Tier 5 37147
Tier 6 93288

**Tiers boosted *10**:
Tier 1 270
Tier 2 750
Tier 3 4508
Tier 4 12393
Tier 5 37147
Tier 6 93288

Config for the last one
![billede](https://user-images.githubusercontent.com/21295394/29749174-727e5132-8b26-11e7-887f-60ccb179a0b2.png)

**Comment by ValkyrieofNight** [comment]
The efficiency configs are all working fine for me on same build. The efficiency configs do not directly change the solar arrays generation rate. You have to use higher efficiency solar cells in the panel for it to generate more energy. If you want to change the output of the panels use s_production_rate.

**Comment by NillerMedDild** [comment]
Ah I see. I was hoping to set standard tier 1 to 600~ rf/t, while having tier 6 on 90.000 rf/t or less, but I guess that's not possible. Thanks for the help.
