### ISSUE TITLE
[1.12.1-2.0.2d] Missing localizations

### ISSUE THREAD

**Issue by Leo40Git** [ValkyrieofNight/EnvironmentalTech#62]
The Multiblock Assembler has no localization whatsoever, and colored Lenses don't have localizations for their tooltips.

**Comment by ValkyrieofNight** [comment]
Is this on 1.12 or 1.12.1?

**Comment by Leo40Git** [comment]
This is on 1.12.1. I... kinda put it in the title...

**Comment by ValkyrieofNight** [comment]
Yes i see that but the 1 version works on both. Ill look into it.

**Comment by SnowShock35** [comment]
This is also in 1.12.2. The localisation for it is missing. If you're having troubles getting it to work try adding a pack.mcmeta and following this https://minecraft.gamepedia.com/Tutorials/Creating_a_resource_pack#pack.mcmeta
