### ISSUE TITLE
Environmental Tech causes Texture Errors

### ISSUE THREAD

**Issue by mcfilmmakers** [ValkyrieofNight/EnvironmentalTech#63]
Using the latest version of Environmental Tech on Forge 2463. I get the following errors:

[https://pastebin.com/sAzGaN4k](https://pastebin.com/sAzGaN4k)

Removing Environmental Tech removes the errors.

**Comment by ValkyrieofNight** [comment]
Texture errors are nothing to worry about. Does not effect the game at all. It's just a block with a missing texture. Disable the thermal electric generator module if you really want to get rid of the error.

**Comment by mcfilmmakers** [comment]
You're kidding right? This is a legitimate bug. A block is missing its texture. It should be closed when the issue is fixed, not closed because you feel like ignoring it.

It's nothing game breaking, sure; But it makes your mod unpresentable to the public in showcases, in playthroughs, and generally, makes it ugly.

I thank your temporary solution, but I frankly don't consider this a closed issue at all.

**Comment by ValkyrieofNight** [comment]
Well I closed this issue because it is in fact already fixed in the next version.

**Comment by zashra00** [comment]
I'm sorry? Is your free use of the free mod not up to your standards? You've gotta be a special type of person to expect a mod in Beta to be perfect

**Comment by mcfilmmakers** [comment]
@ValkyrieofNight Thank you for mentioning that. It makes sense that the issue is closed then.

@zashra00 I beg your pardon? The issue was closed without disclosing the fact that it was already solved. Knowing it is fixed makes sense. I don't expect the mod the be perfect, ever. I expect an issue to remain open until it is fixed, which is what I explicitly said. You have to be a special type to take offense to something so unoffensive.
