### ISSUE TITLE
[1.12] Hit "Void Ore Miner Controller" and get "Direction: -1"

### ISSUE THREAD

**Issue by llloyd4** [ValkyrieofNight/EnvironmentalTech#64]
Right, so, since the Digital book is MIA and I was reading elsewhere to hit a controller with an assembler to get the requirements to build it I did just that. I made a Void Ore Miner Controller Tier 1 and tapped it with a item.environmentaltech.tool_multiblock_assembler.name' (hazarding a guess, the localized name is MIA also >.< ) and it throws back a "Direction: -1" So I *still* don't know what all I need to make to make a Void Ore Miner tier 1. >.< It looks to be oriented correctly, black flat part facing the ground, glowy blue cross part toward the sky, and there is a hole under it that leads to bedrock so... O.o 

Minecraft 1.12
Environmental Tech : 1.12.1-2.0.2d
Valkyrielib: 1.12.1-2.0.2c

**Comment by zashra00** [comment]
Have you tried left clicking for a material list?

**Comment by llloyd4** [comment]
Oh! Ok, it's working now it seems. O.o Weird, I could have sworn I smacked it with the item.environmentaltech.took_multiblock_assembler.name O.o Presumably, since it's not in JEI yet, if I need one of the special ores for ET I just match the ore color with the lens color? For example, Erodium, shows, in JEI that 0.71% with a clear lens and shows nothing under Preferred. But as it's a lavender color, a purple lens is preferred?

**Comment by zashra00** [comment]
The latest version has jei integration

**Comment by llloyd4** [comment]
I'm using version 2.0.2d from August 25th and I see nothing listed for preferred on the ET specific Void Ore Miner only ores like Erodium, Kryonite, etc.

**Comment by zashra00** [comment]
Ahh I misunderstood the question. I don't believe the different lenses colors are implemented at the moment but as far as the et specific ores each one requires a specific tier of miner but each tier of miner can obtain the previous tiers drops as well

**Comment by llloyd4** [comment]
So no preferred color for the specific ET ores? >.< I'm starting this late
game so i am swimming in ores and resources, just need those that I can't
get though normal mining so I can build the higher tier machines.

**Comment by zashra00** [comment]
The higher tierd et machines

**Comment by llloyd4** [comment]
Right, I am asking if I can focus the Void Ore Miner on the ET specific
ores like Erosium or Kryonite, etc?

**Comment by zashra00** [comment]
Atm no they don't have preferred colors but erodium should be craftable if I'm not mistaken

**Comment by llloyd4** [comment]
Only recipe is for Litherite, JEI  has no recipes for Erodium or above.

**Comment by ValkyrieofNight** [comment]
I take it you haven't regenerated the loot tables either. Read the changelogs. The mine rate has been tweaked in more recent versions. Delete the json files for the ore miner in the config folder.

**Comment by llloyd4** [comment]
Well, the version I am running hasn't updated yet, the first and only version I've run (added it manually to the FTB Unstable Pack) has been 2.0.2d and that's the version that I let my world run 8 hours and only got 3 Erosium.

**Comment by ValkyrieofNight** [comment]
That doesn't seem right because I've ran my t1 miner over night and gotten a few stacks of it. You feeding it at least 800rf/t?

**Comment by ValkyrieofNight** [comment]
Also are you chunkloading it?

**Comment by ValkyrieofNight** [comment]
Delete the json files in /config/environmentaltech/multiblocks/void/ore/

**Comment by llloyd4** [comment]
Yeap, it's being fed by a tier 7 DE energy sphere using Draconic tier wireless energy crystals and, yeap, it's my main base, it's all chunkloaded using the built in Forge one. The entire base is green on the map with a red border. What I'll do is flush out the Json files and rerun it for 8 hours again and see.

**Comment by llloyd4** [comment]
![2017-09-04_01 04 45](https://user-images.githubusercontent.com/7238110/30017329-a47c9bc0-910d-11e7-9c52-68f8febe783a.png)

**Comment by llloyd4** [comment]
Ok, noticed some problems with the built in Forge chunk loading so I've installed Chicken Chunks to chunk load my base. Will see after I get up in about 8 hours how the Void Ore Miner did, I am going to idle next to it to be sure it remains chunk loaded.

**Comment by llloyd4** [comment]
Ok, 8 hours later, just 8 Erosium and that's it. 

![2017-09-04_11 58 32](https://user-images.githubusercontent.com/7238110/30036492-b1b97b90-9168-11e7-894e-0a797d754475.png)

**Comment by NisseA** [comment]
I got the same problem but it doesn't matter what I do, it still says "direction -1"
why does it do that?
