### ISSUE TITLE
Tier Progression

### ISSUE THREAD

**Issue by nkendera** [ValkyrieofNight/EnvironmentalTech#65]
The void ore miner feels very slow to gather the next tier crystals. Is it meant to be this slow? We've had our tier one miner running for about a week on a 24/7 server and we only have less than half of what we need for tier two. Is there another way around this or should i just make more void ore miners?

**Comment by ValkyrieofNight** [comment]
Have you regenerated the loot tables? The mine rates have been tweaked in more recent versions of the mod.

**Comment by smartsoldier** [comment]
How do I go about regenerating the loot tables after I update?

**Comment by ValkyrieofNight** [comment]
Delete the json files in /config/environmentaltech/multiblocks/void/ore/

**Comment by FnordMan** [comment]
I have to agree, I had a tier 1 miner running for ~12 hours flat out and I got like 8 erodium crystals. This whole crystals for tiers thing needs a serious rebalance. Not everyone runs a server and can have a game running all the time. Before you ask, yes it was running flat out, it's power bar was full thanks to a nether star generator. 

Personally i'm advocating a return to the old tier system, it worked great for what it was.

**Comment by ValkyrieofNight** [comment]
If you really want them to mine faster edit the loot tables. Its not hard coded. Balances will come when I have some free time to actually play the mod.

**Comment by Guybrush0** [comment]
adding to this, erodium+ do not have lens assignments, so you cannot focus them at the moment, this would probably fix any issues that people have been having

**Comment by ValkyrieofNight** [comment]
They will have lens assignments in the future. I'm just still thinking how I want to do that for the crystals. Might add a new lens for just the crystals or one for each but am not sure how i'm going to go about this yet.

**Comment by ValkyrieofNight** [comment]
The Latest version has another bump in mine rates but youll need to regen loot tables again.

**Comment by Dragnier** [comment]
9 erodium in 4-5 hours. I think the main thing here is the lack of preferred lens. If you added one and had it so that the erodium preferred lens required 2-4 erodium crystal to craft, that would make it less grindy but also not too easy. Beyond that, you could make each preferred lens an upgrade of the previous one; each also requiring the tier of crystal it was for.

**Comment by ValkyrieofNight** [comment]
Yeah that's kind of the plan but lately I've been swamped with work so I haven't had the time. There may be an update with a solution in the next few days.

**Comment by Dragnier** [comment]
No rush, was just offering a suggestion.

**Comment by ValkyrieofNight** [comment]
Added a lens for the crystals
