### ISSUE TITLE
[1.12.1] - Preferred crystal not shown in JEI

### ISSUE THREAD

**Issue by Protheus** [ValkyrieofNight/EnvironmentalTech#66]
The preferred crystals are not shown in JEI with environmentaltech-1.12.1-2.0.2d.

Maybe you can add a tooltip to the crystal telling which is preferred as I'm color blind and no idea which color to use

![2017-09-15_07 48 03](https://user-images.githubusercontent.com/1455178/30468250-6ccd257e-99ea-11e7-80d9-a3308d1d124b.png)
![2017-09-15_07 47 29](https://user-images.githubusercontent.com/1455178/30468251-6ccfcaea-99ea-11e7-95fe-640962372004.png)
![2017-09-15_07 47 43](https://user-images.githubusercontent.com/1455178/30468249-6cccfb44-99ea-11e7-8290-a574b2b1e123.png)
![2017-09-15_07 47 47](https://user-images.githubusercontent.com/1455178/30468252-6cd0ce68-99ea-11e7-8c89-e3f356d9fca4.png)

**Comment by ValkyrieofNight** [comment]
They do not have a preferred lens yet, These will come in the future however.

**Comment by Arkyo** [comment]
The problem occurs in 1.11.2 too

**Comment by tyler489** [comment]
According to the confjg the prefered type is the tier of void miner that matches the crystal .

**Comment by ValkyrieofNight** [comment]
The preferred lenses for the crystals have not been implemented yet but will be soon. As far as 1.11 it's kinda broken and a port for ET 2 may be coming.

**Comment by Protheus** [comment]
I just bumped up the % for now... ET2 cant wait

**Comment by Protheus** [comment]
as the crystal lenses are now in, this issue is fixed so can be closed

**Comment by Hajitorus** [comment]
It's also noted in the changelog that you might need to update the JSONs in your existing installs. I had to edit the tier_n.json files for at least Horizons III and DW20's pack, details here: https://forum.feed-the-beast.com/threads/env-tech-config-issue.267070/
