### ISSUE TITLE
Not all ores that are in the void ore miner's config are actually mined

### ISSUE THREAD

**Issue by MaienM** [ValkyrieofNight/EnvironmentalTech#67]
Many of the ores that are in the void ore miner's autogenerated configs are never actually mined. The first one I noticed missing was osmium ore, but when looking at the config I noticed a bunch of other ores that are also never output by my void ore miner such as ardite and cobalt. JEI also doesn't have these ores listed as being generated by the void ore miner.

I run a custom pack, [modlist](https://github.com/ValkyrieofNight/EnvironmentalTech/files/1312587/modlist.2.txt), [latest.log](https://github.com/ValkyrieofNight/EnvironmentalTech/files/1312585/latest.log.txt)

**Comment by ValkyrieofNight** [comment]
Yeah a fix will be coming for this issue in the next update 👍

**Comment by ValkyrieofNight** [comment]
Fixed in latest update.
