### ISSUE TITLE
TileLaserCore is missing a mapping

### ISSUE THREAD

**Issue by bdew** [ValkyrieofNight/EnvironmentalTech#68]
Crash report: https://gist.github.com/bdew/ba8568f9addde014f058af176b1ebe79

After updating to 2.0.4a started getting this crash when trying to load an old world.

**Comment by ValkyrieofNight** [comment]
Thanks will get a fix out today.

**Comment by ValkyrieofNight** [comment]
Fixed in latest version of ValkyrieLib
