### ISSUE TITLE
crash client clicking assembler in gui (environmentaltech-1.10.2-0.10.5g) on server

### ISSUE THREAD

**Issue by SDUBZ** [ValkyrieofNight/EnvironmentalTech#7]
forge:1.10.2-2121
[crash-2016-11-05_23.40.26-client.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/573173/crash-2016-11-05_23.40.26-client.txt)

**Comment by SDUBZ** [comment]
tested also in singleplayer same thing happens
[crash-2016-11-05_23.59.12-client.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/573187/crash-2016-11-05_23.59.12-client.txt)

jei version: jei_1.10.2-3.13.2.348

**Comment by ValkyrieofNight** [comment]
That looks like a JEI problem to me. I cannot seem to replicate the crash with the same versions of ET, ValkyrieLib and JEI. Try updating JEI to see if that fixes the problem.

**Comment by SDUBZ** [comment]
i wish i could update jei so easily im waiting on the armorplus guy to intergrate with the newer versions of jei, but thanks for looking into it anyways :D

**Comment by SDUBZ** [comment]
umm i got a idea what if you test in same enviroment as mine maybe you will notice something i havent noticed heres my pack for further testing https://minecraft.curseforge.com/projects/sdubzcraft

**Comment by SDUBZ** [comment]
hey i updated to the latest jei and armorplus doesnt crash and your guide works again :D

**Comment by ValkyrieofNight** [comment]
Awesome that's good to know.
