### ISSUE TITLE
[1.12.2] Crash on Startup -- Class not found

### ISSUE THREAD

**Issue by ElvenChaos** [ValkyrieofNight/EnvironmentalTech#71]
I get the following "class not found" crash on startup: https://pastebin.com/jFgyEZsE

Forge: 14.23.0.2495
MC: 1.12.2
EnvTech: 1.12.X-2.0.3a
ValkLib: 1.12-2.0.4b
EnvMat: 1.12.X-1.0.4a

**Comment by ValkyrieofNight** [comment]
Update ET to 2.0.4a

**Comment by ElvenChaos** [comment]
Woops. I thought I had it updated, sorry about that.

**Comment by ValkyrieofNight** [comment]
Haha no probs it happens.
