### ISSUE TITLE
[1.10.2] Odd ore distribution when using anything else but a chest with the Void Ore Miner

### ISSUE THREAD

**Issue by Ieldra2** [ValkyrieofNight/EnvironmentalTech#73]
This is ET version 0.10.6b in SkyFactory 3. I found that several types of inventories don't work or don't work as intended as receptacles for the ore created by the Void Ore Miner. Storage Drawers (from the mod of the same name) and EnderIO Vacuum Chests don't work at all, and when using an EnderIO Dimensional Transceiver I don't get any iron when using the white lens and lots of RFtools dimensional shard ore, and I don't get any gold when using the yellow lens but tons of glowstone blocks. Remove the transceiver and replace it with a chest from the Iron Chests mod, and the ore weights are as intended. The effect gets more pronounced when using more Accuracy modifiers, i.e. I get iron/gold very rarely when using no Accuracy modifiers and a dimensional transceiver, and none at all when using 10 in a tier 4 miner.

**Comment by zashra00** [comment]
That literally makes no sense seeing as how the void miners have their own loot tables that are generated when the mod is first run that sounds more like an issue with eio not wanting to share loot
