### ISSUE TITLE
1.12.2( magenta colored lens no recipe

### ISSUE THREAD

**Issue by SDUBZ** [ValkyrieofNight/EnvironmentalTech#78]
Forge:1.12.2-2542
ET:1.12-2.0.4

**Comment by C0rn3j** [comment]
![image](https://user-images.githubusercontent.com/1641362/32920620-3ee61dca-cb2a-11e7-8bd1-b3154babf91c.png)
@ValkyrieofNight Is this why I don't see any item for the Litherite and Erodium when I look at what items I can get from void miner?

I wouldn't wanna open a useless issue. 

MC 1.12.2; Forge 2544, 1.12.X-2.0.4a.jar
