### ISSUE TITLE
[1.12.2] Weather2 Breaks Functionality of Environmentaltech Solar producing power

### ISSUE THREAD

**Issue by Morpheus1101** [ValkyrieofNight/EnvironmentalTech#79]
Forge: *.1.2559
Weather2:  2.5.5-a
Coroutil:  1.1.22-a
Environmentaltech:  2.0.5a

After stripping down my pack i discovered that it isnt untill the weather2 mod is included that Solar power breaks in all of ET machines.

![2017-11-23_19 40 15](https://user-images.githubusercontent.com/10524952/33166484-2593c0a0-d086-11e7-8f10-6def681fcf4e.png)

**Comment by Corosauce** [comment]
By default weather2 locks server side rain and thunder off to do local things. I dont know how their solar works but it seems odd that it'd break with the rain/thunder off always, I'd expect it to break if rain/thunder was always on, weird...

Either way, there's a more mod compatible mode called global overcast, see if it helps, turn it on in the Misc.cfg file or set 'storms when' to global overcast in the ingame weather gui...... But I'm assuming thats why it breaks.

**Comment by Morpheus1101** [comment]
I forgot this was still open, its long since been resolved in later vers of Weather2, not sure what it was back then that was breaking it.
