### ISSUE TITLE
[Feature Request] Silent Gems Ores

### ISSUE THREAD

**Issue by scottosx** [ValkyrieofNight/EnvironmentalTech#8]
I have customized the minable.json config file to include all of the gemstones from Silent Gems https://minecraft.curseforge.com/projects/silents-gems The colors for lasers have been assigned as well.

Silent Gems is a great mod and is ideal to give more reasons to craft the color lenses.

Here is the file as a text document. Tested and works.

[minable.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/573855/minable.txt)

**Comment by ValkyrieofNight** [comment]
Will add those to the defaults. Thanks
