### ISSUE TITLE
[1.12.2] The void ore miner does not work.

### ISSUE THREAD

**Issue by Maurj** [ValkyrieofNight/EnvironmentalTech#81]
i am playing with the direwolf20 modpack for 1.12, and after assembling the multiblock using the wand, it never says to me that the multiblock assembly is complete, despite me having all of the parts needed for it, it accepts power, but it doesnt run at all.

**Comment by TOLoneWolf** [comment]
Seems to work fine for me. Did you clear a path to bedrock? Does it show a white beam going down? After suppying power does it consume it?

**Comment by skylersa** [comment]
I have the same problem in the same pack, it has a white beam to bedrock, it is not consuming power but it is filling it's internal buffer (according to the one probe) and no ores are going into the chest on top. I tried it with a redstone signal and without, neither works. **Never mind I am getting ores, it is just extremely slow.**

**Comment by ValkyrieofNight** [comment]
Will take a look

**Comment by NisseA** [comment]
playing on the same pack but I get the "direction -1" and no beam at all... I've made a hole down to the bedrock, I've assembled the void miner with all the blocks thats needed.

**Comment by blaklafter** [comment]
I also have the same problem.  Void ore miner will auto assemble and accept power (with LoS to bedrock), but does not function (beam is not visible).  Running Direwolf20 1.12-1.1.12.2-1.4.0.  I even manually updated the mod to 2.0.6b but this did not fix the issue.

**Comment by NisseA** [comment]
blaklafter, realized it has to do with missing item... I was missing like 4 blocks. disemble the void and check again if you have all the parts!

**Comment by boatrite** [comment]
The problem I believe is that the tooltip for the (at the least) Tier 2 Ore Miner is incorrect.

Here is the Tier 2 block list

![image](https://user-images.githubusercontent.com/5781611/34853900-eb5f565a-f6fb-11e7-8256-c00098d79f28.png)

Here is the block list for the Tier 1 controller and the next tier. Notice it includes the 4 Null Modifiers.

![image](https://user-images.githubusercontent.com/5781611/34853919-08329b34-f6fc-11e7-9e92-9fdd54479c1c.png)

**Comment by scotty9090** [comment]
The tool tip is correct, it has just scrolled out of the chat window.  Hit '/' to open chat and you'll see it's there.
