### ISSUE TITLE
NuclearCraft Ores

### ISSUE THREAD

**Issue by Nexus35** [ValkyrieofNight/EnvironmentalTech#82]
As of version 1.12.x- 2.0.3a, the NuclearCraft ores are not being generated by the Void Ore Miner.

The unique ores that are missing are the following:

"Thorium Ore", "Boron Ore", "Lithium Ore", "Magnesium Ore"

The other ores are already a part of the ore dictionary and are being generated. ("Uranium Ore" for example).

**Comment by Reanmachine** [comment]
Note: Here's the ore dictionary entries...

https://github.com/turbodiesel4598/NuclearCraft/blob/04692cd417efae7c87bfbdf379b12c368935c89b/src/main/java/nc/handler/OreDictHandler.java#L15-L19

```
oreThroium, oreBoron, oreLithium, oreMagnesium
```

**Comment by ValkyrieofNight** [comment]
Thanks added to the defaults.
