### ISSUE TITLE
Blocks safe to use as decoration? [1.12.2]

### ISSUE THREAD

**Issue by Vyraal1** [ValkyrieofNight/EnvironmentalTech#84]
Hi,

I really like a lot of the textures of the structures and blocks in the mod, and was wondering if some of the blocks (not including the controllers) could be used for decoration as I'm not sure if they are tile entities or not. Specifically I was inspired to use some of them as part of Modular Machinery custom multiblocks and wanted to know if this could have any downside.

Thanks,

**Comment by ValkyrieofNight** [comment]
Yeah all the blocks except for controllers are safe for decoration.
