### ISSUE TITLE
RFE: Display size of the stucture together with the required resources

### ISSUE THREAD

**Issue by MatthiasMann** [ValkyrieofNight/EnvironmentalTech#87]
In 1.12.2 the assembler only shows the number of blocks required to build the structure and can assemble the structure.

But without knowing how high/wide it is one can not plan the placement of the controller in advance.

This makes the mod very hard to use - other mods include features like projectors or a book with a 3D animation of the assembled structure which gives a very good idea how large and what shape it is.

**Comment by Protheus** [comment]
Go creative, create one and measure it for now till there is a better way. As for hight. Tiers from 1 are 1 block higher.

**Comment by ValkyrieofNight** [comment]
This will be in the guide once its implemented fully.

**Comment by ValkyrieofNight** [comment]
Version 2.0.12a contains info in guide
