### ISSUE TITLE
WAILA shows White Lens for other colors

### ISSUE THREAD

**Issue by scottosx** [ValkyrieofNight/EnvironmentalTech#9]
This is a black lens but WAILA lists it as white.

![2016-11-06_07 57 33](https://cloud.githubusercontent.com/assets/5866215/20038337/841988e2-a3f7-11e6-8eda-5308c8fb27e9.png)

**Comment by xenoflot** [comment]
That's a problem with WAILA. It misreports all kinds of things. Sadly WAILA hasn't been updated for a few months.

**Comment by ValkyrieofNight** [comment]
Yeah. Have you tried The One Probe? Its a very good WAILA replacement.
