### ISSUE TITLE
Network Disconnect: A fatal error has occurred, this connection is terminated

### ISSUE THREAD

**Issue by Mohron** [ValkyrieofNight/EnvironmentalTech#90]
- mod-tabbychat-2.3.3-mc1.12.2
- liteloader-1.12.2-SNAPSHOT-release
- environmentaltech-1.12.2-2.0.6b
- Forge-14.23..1.2565

When using Tabby Chat with environmental tech clicking a controller disconnects you from an smp server.
https://hastebin.com/jojuwabama.php

**Comment by killjoy1221** [comment]
Please handle your packets properly. Wrap all your packet logic inside `Minecraft.getMinecraft().addScheduledTask()`
