### ISSUE TITLE
[1.12.2] Ores?

### ISSUE THREAD

**Issue by Skaphegor** [ValkyrieofNight/EnvironmentalTech#91]
I activated the ores but they do not spawn or work.
![2017-12-26_17 09 58](https://user-images.githubusercontent.com/26455012/34360512-c9909850-ea61-11e7-9116-f4fc13608a1e.png)

**Comment by ValkyrieofNight** [comment]
Yeah they are not fully implemented yet. No ore generation in for them yet. Will add soon

**Comment by JonasCiss** [comment]
It was in the config file so I tought it was finished.

**Comment by ValkyrieofNight** [comment]
@Zygus42  Yeah I will do that.

**Comment by ValkyrieofNight** [comment]
No longer updating the 1.12.2 version
