### ISSUE TITLE
1.12 Spelling mistakes causing NuclearCraft ores to not be in spawns

### ISSUE THREAD

**Issue by BillboardEric** [ValkyrieofNight/EnvironmentalTech#92]
![image](https://user-images.githubusercontent.com/8685981/34400805-f579cca0-eb62-11e7-8f69-8714d6535f70.png)
This should be Thorium, not Throium

![image](https://user-images.githubusercontent.com/8685981/34400813-04416784-eb63-11e7-895c-53a35f90b411.png)
Silver instead of Siver

**Comment by ValkyrieofNight** [comment]
fixed and will be in next release
