### ISSUE TITLE
1.12.2 Direction -1 and no beam

### ISSUE THREAD

**Issue by NisseA** [ValkyrieofNight/EnvironmentalTech#95]
Ive placed the void miner and I've made a hole down to the bedrock. its getting power but I got no beam and it gives me "direction -1" in the chat when I'm right clicking it with the assembler.

whats wrong?

**Comment by Hajitorus** [comment]
NisseA: In #81 you say that you resolved your issue by placing the missing blocks the miner required. Does this mean your issue is now resolved and this bug can be closed?

**Comment by SarahRuby** [comment]
Left click with Assembler to Controller to see what you need.
And make sure you have enough of them.

**Comment by NisseA** [comment]
yeah its resolved!

**Comment by PG-Fuury** [comment]
Then close the issue please
