### ISSUE TITLE
[1.12.2] Obtaining sufficent quantities of crystals to do anything beyond Tier1

### ISSUE THREAD

**Issue by Morpheus1101** [ValkyrieofNight/EnvironmentalTech#98]
After literally 2 days straight and running 4 void miners ive barely gotten enough crystals to make the crystal lense let alone being able to gather any in sufficient quantities to be worthwhile doing anything beyond Tier1 .. is there other means in progress or a way to speed things up short of building more an dmore void miners?

**Comment by mctom987** [comment]
What pack are you running? I used ETech in Direwolf20 and FTB Revelation for 1.12.2, and neither require a crystal lens.  Even the Tier 6 takes any "etLaserLens" which can be any of the colored or clear variants.

I suspect your modpack is changing the recipes, possibly to make ETech harder to progress in.

**Comment by Morpheus1101** [comment]
Nope, using default configs and the Crystal Laser Lens was something mentioned in #66

**Comment by CharCharthemonkey** [comment]
ive noticed it too where getting decent ammounts of the green purple and dark purple crystals is really slow

**Comment by ValkyrieofNight** [comment]
I'm pretty sure this should no longer be an issue. Please re-open issue if it is :P
