### ISSUE TITLE
Blocks not breaking

### ISSUE THREAD

**Issue by marciox25** [ValkyrieofNight/EnvironmentalTech#99]
As described in the title, when a structure is operating, when you try to break a block, eg: to swap lenses, The block doest breaks, it just goes back to where it was. Although, other blocks, not from the structure, you can break them fine.
Version: environmentaltech-1.12.2-2.0.6b

**Comment by marciox25** [comment]
By righclicking the controller, till you get the owner and positions, it allows it back to be breakable .... not sure why this is happening

**Comment by mctom987** [comment]
You can shift-use the Assembler to instantly break parts, including those protected by that mechanism.

**Comment by ValkyrieofNight** [comment]
Version 2.0.12a contains fix
